In [1]:
import pandas as pd
import scanpy as sc

# Sample level

In [19]:
data = pd.read_csv('./visual/sample_all.csv', index_col=0)
data

,tissue,disease_name,disease,age,age_stage,sex,technology,others
sample,,,,,,,,
10x_datasets_10-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN
10x_datasets_1-1,blood,Healthy,healthy,32.5,30_40,Male,10x multiome,NaN
10x_datasets_2-1,blood,Healthy,healthy,32.5,30_40,Male,10x multiome,NaN
10x_datasets_3-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN
10x_datasets_4-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN
...,...,...,...,...,...,...,...,...
Wimmers_Cell_2023-71_CC0594,blood,COVID-19,acute-omicron,8.6,0_1,Male,10x multiome,NaN
Wimmers_Cell_2023-72_CC0688,blood,COVID-19,acute-omicron,7.5,0_1,Male,10x multiome,NaN
Wimmers_Cell_2023-73_CC0710,blood,COVID-19,acute-omicron,6.1,0_1,Female,10x multiome,NaN
Wimmers_Cell_2023-74_CC0716,blood,COVID-19,acute-omicron,5.75,0_1,Female,10x multiome,NaN
Wimmers_Cell_2023-76_CC0829,blood,COVID-19,acute-omicron,3.8,0_1,Male,10x multiome,NaN

In [20]:
data['technology'].value_counts()

technology
10x multiome    132
TEA-seq          23
DOGMA-seq        16
ReDeeM           16
SHARE-seq         7
NEAT-seq          2
Name: count, dtype: int64

In [3]:
132+23+16+16+2+12

201

In [6]:
data['tissue'].value_counts()

tissue
blood          159
bone marrow     37
Name: count, dtype: int64

In [7]:
data['disease_name'].value_counts()

disease_name
Healthy             133
COVID-19             44
HIV-1                 9
Melanoma              8
Pearson syndrome      2
Name: count, dtype: int64

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

sample_types = ['Blood', 'Bone marrow']
cell_counts = {
    'Healthy': [96, 37], 
    'HIV-1': [9, 0], 
    'COVID-19': [44, 0],
    'Melanoma': [8, 0],
    'Pearson syndrome':[2, 0]
}

# Calculate x-axis positions and set bar width
x = np.arange(len(sample_types))
width = 0.6

# Plot stacked bar chart
# Initialize the bottom coordinates for the first layer of bars
bottoms = np.zeros(len(sample_types))

for label, counts in cell_counts.items():
    plt.bar(x, counts, width, label=label, bottom=bottoms)
    # Update the bottom coordinates for the next layer of stacking
    bottoms += np.array(counts)

# Customize chart labels and title
plt.ylabel('Sample number')
plt.xlabel('Sample type')
plt.title('Sample number by Disease and tissue')
plt.xticks(x, sample_types) # Set x-axis tick labels
plt.legend(title='Disease')

# Adjust layout, save, and display the plot
plt.tight_layout()
plt.savefig('./visual/sample_disease_tissue.pdf', format='pdf')
plt.show()

In [14]:
a = pd.DataFrame(data['age_stage'].value_counts())
a

              count
age_stage
notAvailable     51
30_40            42
0_1              29
20_30            14
1_2              14
60_70            13
50_60            10
40_50             8
10_20             8
70_80             7

In [ ]:
import matplotlib.pyplot as plt

categories = a.index.tolist()
values = a['count'].tolist()

plt.figure(figsize=(8,6))
bars = plt.bar(categories, values, color='black')

plt.title('Number of donors by Smoking status')
plt.xlabel('Smoking status')
plt.ylabel('Number of donors')

plt.xticks(rotation=90)

plt.savefig('./visual/sample_age.pdf', format='pdf')
plt.show()

In [23]:
a = pd.DataFrame(data['sex'].value_counts())
a

              count
sex
Female           76
Male             72
notAvailable     48

In [ ]:
import matplotlib.pyplot as plt

labels = ['Female', 'Male', 'notAvailable']
values = [76, 72, 53]
colors = ['#688EC9', '#BE1B1F', '#A9AAAA']

fig, ax = plt.subplots()
ax.axis('equal')  

plt.pie(values, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)

plt.legend(labels, loc="upper right")

plt.savefig('./visual/sample_sex.pdf', format='pdf')
plt.show()

In [3]:
196-7+12

201

In [8]:
76/201

0.3781094527363184

In [5]:
72/201

0.3582089552238806

In [6]:
53/201

0.263681592039801

# Cell levell

In [11]:
data = pd.read_csv('./visual/sample_all.csv', index_col=0)
data['sample_'] = data.index.tolist()
data

,tissue,disease_name,disease,age,age_stage,sex,technology,others,sample_
sample,,,,,,,,,
10x_datasets_10-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN,10x_datasets_10-1
10x_datasets_1-1,blood,Healthy,healthy,32.5,30_40,Male,10x multiome,NaN,10x_datasets_1-1
10x_datasets_2-1,blood,Healthy,healthy,32.5,30_40,Male,10x multiome,NaN,10x_datasets_2-1
10x_datasets_3-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN,10x_datasets_3-1
10x_datasets_4-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN,10x_datasets_4-1
...,...,...,...,...,...,...,...,...,...
Wimmers_Cell_2023-71_CC0594,blood,COVID-19,acute-omicron,8.6,0_1,Male,10x multiome,NaN,Wimmers_Cell_2023-71_CC0594
Wimmers_Cell_2023-72_CC0688,blood,COVID-19,acute-omicron,7.5,0_1,Male,10x multiome,NaN,Wimmers_Cell_2023-72_CC0688
Wimmers_Cell_2023-73_CC0710,blood,COVID-19,acute-omicron,6.1,0_1,Female,10x multiome,NaN,Wimmers_Cell_2023-73_CC0710
Wimmers_Cell_2023-74_CC0716,blood,COVID-19,acute-omicron,5.75,0_1,Female,10x multiome,NaN,Wimmers_Cell_2023-74_CC0716
Wimmers_Cell_2023-76_CC0829,blood,COVID-19,acute-omicron,3.8,0_1,Male,10x multiome,NaN,Wimmers_Cell_2023-76_CC0829

In [14]:
adata = sc.read_h5ad('./processed/adata_rna_celltypist_cellhint.h5ad')
adata

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType', 'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score', 'level_1', 'level_2', 'level_3'
    uns: 'level_1_colors', 'level_2_colors', 'log1p', 'neighbors', 'over_clustering', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'

In [16]:
cell = adata.obs
cell

,dataset,barcode,sample,cellType,predicted_labels,over_clustering,majority_voting,conf_score,level_1,level_2,level_3
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Regulatory T cells,67,Regulatory T cells,0.511893,Lymphoid,T cells,Regulatory T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Tem/Effector helper T cells,264,Tcm/Naive helper T cells,0.011004,Lymphoid,T cells,Tem/Effector helper T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,CD16- NK cells,48,Tem/Effector helper T cells,0.022152,Lymphoid,ILC,CD16- NK cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Tem/Trm cytotoxic T cells,219,Tcm/Naive helper T cells,0.953910,Lymphoid,T cells,Tem/Trm cytotoxic T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Tcm/Naive helper T cells,70,Tcm/Naive helper T cells,0.222813,Lymphoid,T cells,Tcm/Naive helper T cells
...,...,...,...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,Small pre-B cells,238,Small pre-B cells,0.020311,Lymphoid,B-cell lineage,Small pre-B cells
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,Small pre-B cells,238,Small pre-B cells,0.621049,Lymphoid,B-cell lineage,Small pre-B cells
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,Memory B cells,95,Naive B cells,0.999996,Lymphoid,B cells,Memory B cells
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,Tem/Temra cytotoxic T cells,43,Tem/Trm cytotoxic T cells,0.229349,Lymphoid,T cells,Tem/Temra cytotoxic T cells
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,pDC,322,pDC,0.999995,Myeloid,pDC,pDC

In [17]:
all = pd.merge(cell, data, left_on='sample', right_on='sample_')
all.index = adata.obs_names.tolist()
all

,dataset,barcode,sample,cellType,predicted_labels,over_clustering,majority_voting,conf_score,level_1,level_2,level_3,tissue,disease_name,disease,age,age_stage,sex,technology,others,sample_
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Regulatory T cells,67,Regulatory T cells,0.511893,Lymphoid,T cells,Regulatory T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN,Chen_Nat_Methods_2022-lane1
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Tem/Effector helper T cells,264,Tcm/Naive helper T cells,0.011004,Lymphoid,T cells,Tem/Effector helper T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN,Chen_Nat_Methods_2022-lane1
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,CD16- NK cells,48,Tem/Effector helper T cells,0.022152,Lymphoid,ILC,CD16- NK cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN,Chen_Nat_Methods_2022-lane1
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Tem/Trm cytotoxic T cells,219,Tcm/Naive helper T cells,0.953910,Lymphoid,T cells,Tem/Trm cytotoxic T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN,Chen_Nat_Methods_2022-lane1
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Tcm/Naive helper T cells,70,Tcm/Naive helper T cells,0.222813,Lymphoid,T cells,Tcm/Naive helper T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN,Chen_Nat_Methods_2022-lane1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,Small pre-B cells,238,Small pre-B cells,0.020311,Lymphoid,B-cell lineage,Small pre-B cells,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN,Weng_Nature_2024_7-1
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,Small pre-B cells,238,Small pre-B cells,0.621049,Lymphoid,B-cell lineage,Small pre-B cells,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN,Weng_Nature_2024_7-1
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,Memory B cells,95,Naive B cells,0.999996,Lymphoid,B cells,Memory B cells,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN,Weng_Nature_2024_7-1
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,Tem/Temra cytotoxic T cells,43,Tem/Trm cytotoxic T cells,0.229349,Lymphoid,T cells,Tem/Temra cytotoxic T cells,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN,Weng_Nature_2024_7-1
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,pDC,322,pDC,0.999995,Myeloid,pDC,pDC,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN,Weng_Nature_2024_7-1

In [18]:
all['technology'].value_counts()

technology
10x multiome    909252
SHARE-seq       874480
TEA-seq         362002
DOGMA-seq       178607
ReDeeM          129830
NEAT-seq          8457
Name: count, dtype: int64

In [7]:
909252+53718

962970

In [1]:
1077697-874480

203217

In [43]:
all['tissue'].value_counts()

tissue
blood          1384931
bone marrow    1077697
Name: count, dtype: int64

In [48]:
all['disease_name'].value_counts()

disease_name
Healthy             1961203
COVID-19             298184
HIV-1                104222
Melanoma              69656
Pearson syndrome      29363
Name: count, dtype: int64

In [49]:
1384931-104222-298184-69656-29363

883506

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

sample_types = ['Blood', 'Bone marrow']
cell_counts = {
    'Healthy': [883506, 1077697], 
    'HIV-1': [104222, 0], 
    'COVID-19': [298184, 0],
    'Melanoma': [69656, 0],
    'Pearson syndrome':[29363, 0]
}

x = np.arange(len(sample_types))
width = 0.6

bottoms = np.zeros(len(sample_types))
for label, counts in cell_counts.items():
    plt.bar(x, counts, width, label=label, bottom=bottoms)
    bottoms += np.array(counts)

plt.tight_layout()
plt.savefig('./visual/cell_disease_tissue.pdf', format='pdf')
plt.show()

In [53]:
a = pd.DataFrame(all['age_stage'].value_counts())
a

                count
age_stage
notAvailable  1270902
30_40          291895
0_1            202066
50_60          200822
10_20          132522
20_30           98910
1_2             86145
60_70           76713
70_80           54799
40_50           47854

In [ ]:
import matplotlib.pyplot as plt

categories = a.index.tolist()
values = a['count'].tolist()

plt.figure(figsize=(8,6))
bars = plt.bar(categories, values, color='black')

plt.title('Number of donors by Smoking status')
plt.xlabel('Smoking status')
plt.ylabel('Number of donors')

plt.xticks(rotation=90)

plt.savefig('./visual/cell_age.pdf', format='pdf')
plt.show()

In [55]:
a = pd.DataFrame(all['sex'].value_counts())
a

                count
sex
notAvailable  1249140
Female         722462
Male           491026

In [2]:
1249140-874480

374660

In [ ]:
import matplotlib.pyplot as plt

labels = ['Female', 'Male', 'notAvailable']
values = [722462, 491026, 428378]
colors = ['#688EC9', '#BE1B1F', '#A9AAAA']

fig, ax = plt.subplots()
ax.axis('equal')  

plt.pie(values, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)

plt.legend(labels, loc="upper right")

plt.savefig('./visual/cell_sex.pdf', format='pdf')
plt.show()

In [11]:
1249140-874480+53718+722462+491026

1641866

# UMAP of SHARE-seq

In [2]:
adata = sc.read_h5ad('processed/adata_rna_celltypist_cellhint.h5ad')
adata

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType', 'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score', 'level_1', 'level_2', 'level_3'
    uns: 'level_1_colors', 'level_2_colors', 'log1p', 'neighbors', 'over_clustering', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'

In [4]:
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = ['Arial']  
plt.rcParams['font.family'] = 'sans-serif'   

sc.set_figure_params(dpi=300)

In [22]:
adata.obs['technology'] = all['technology'].tolist()

In [ ]:
sc.pl.umap(adata, color='technology', save='_technology')

# Cell annotation

In [ ]:
import matplotlib.pyplot as plt

data = [1292269, 349597]
labels = ['Category 1', 'Category 2']  
colors = ['#66c2a5', '#fc8d62']      

plt.figure(figsize=(6, 6))  
plt.pie(data, labels=labels, autopct='%1.1f%%', startangle=90, colors=colors, textprops={'fontsize': 12})


plt.title('Pie Chart Example', fontsize=16)

plt.savefig("pie_chart_example.pdf", format="pdf", bbox_inches="tight")

plt.show()

In [ ]:
import matplotlib.pyplot as plt

data = {
    'cellType_chetah_level2': 0.15520762318062262,
    'cellType_scarch_level2': 0.3342879849319298,
    'cellType_scmap_level2': 0.45881236801316133,
    'cellType_singler_level2': 0.5479037259270322,
    'cellType_actinn_level2': 0.5641511171435668,
    'cellType_singlecellnet_level2': 0.798645638021186,
    'cellType_celltypist_level2': 0.8091852392961527,
    'cellType_scpred_level2': 0.8188983872552851
}

labels = list(data.keys())
values = list(data.values())

plt.figure(figsize=(10, 6))


plt.bar(labels, values, color='skyblue', edgecolor='black')

plt.title('Performance of Different Methods', fontsize=16)
plt.xlabel('Methods', fontsize=14)
plt.ylabel('Scores', fontsize=14)

plt.xticks(rotation=45, ha='right', fontsize=12)

for i, v in enumerate(values):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center', fontsize=10)

plt.savefig("bar_chart.pdf", format="pdf", bbox_inches="tight")

plt.tight_layout() 
plt.show()

In [ ]:
import matplotlib.pyplot as plt

data = [1476837, 165029]
labels = ['Category 1', 'Category 2'] 
colors = ['#66c2a5', '#fc8d62']       

plt.figure(figsize=(6, 6))  
plt.pie(data, labels=labels, autopct='%1.1f%%', startangle=90, colors=colors, textprops={'fontsize': 12})

plt.title('Pie Chart Example', fontsize=16)

plt.savefig("pie_chart.pdf", format="pdf", bbox_inches="tight")

plt.show()

# Benchmark

In [1]:
from colour import Color
from matplotlib.colors import LinearSegmentedColormap


def make_colormap(colors, show_palette=False):
    color_ramp = LinearSegmentedColormap.from_list(
        "my_list", [Color(c1).rgb for c1 in colors]
    )
    if show_palette:
        plt.figure(figsize=(15, 3))
        plt.imshow(
            [list(np.arange(0, len(colors), 0.1))],
            interpolation="nearest",
            origin="lower",
            cmap=color_ramp,
        )
        plt.xticks([])
        plt.yticks([])
    return color_ramp


def reject_outliers(data, m=2):
    return data[abs(data - np.mean(data)) < m * np.std(data)]


def rgb2hex(vals, rgbtype=1):
    """Converts RGB values in a variety of formats to Hex values.

    @param  vals     An RGB/RGBA tuple
    @param  rgbtype  Valid valus are:
                         1 - Inputs are in the range 0 to 1
                       256 - Inputs are in the range 0 to 255

    @return A hex string in the form '#RRGGBB' or '#RRGGBBAA'"""
    if len(vals) != 3 and len(vals) != 4:
        raise Exception(
            "RGB or RGBA inputs to RGBtoHex must have three or four elements!"
        )
    if rgbtype != 1 and rgbtype != 256:
        raise Exception("rgbtype must be 1 or 256!")

    # Convert from 0-1 RGB/RGBA to 0-255 RGB/RGBA
    if rgbtype == 1:
        vals = [255 * x for x in vals]

    # Ensure values are rounded integers, convert to hex, and concatenate
    return "#" + "".join(["{:02X}".format(int(round(x))) for x in vals])


metric_batch_colormap = make_colormap(
    [
        "#4D004A",
        "#88419D",
        "#8C96C6",
        "#BFD3E6",
        "#CEF5FD",
    ]
)

metric_bio_colormap = make_colormap(
    [
        "#49006A",
        "#AE007E",
        "#F768A1",
        "#FCC5C0",
        "#FFE9DE",
    ]
)

metrics_overall_colormap = make_colormap(
    [
        "#0A1D58",
        "#235FA8",
        "#40B6C4",
        "#C7E9B4",
        "#FDFFAB",
    ]
)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
# df = pd.read_csv("./bm_demo.csv", index_col=0)

# for i in range(df.shape[1]):
#     arr = df.iloc[:, i].to_numpy().flatten()
#     df.iloc[:, i] = (arr - arr.min()) / (arr.max() - arr.min())

# metrics_batch = [
#     "silhouette_batch ASW (study_name)",
#     "Graph connectivity",
#     "pcr_comparison",
# ]

# metrics_bio = [
#     "silhouette_score (label)",
#     "isolated_label_asw (study_name)",
#     "isolated_label_f1 (study_name)",
# ]

# df = df[df.index != "X_PCA"]

# df = df.loc[:, metrics_batch + metrics_bio]
# df = df.iloc[::-1]
# l = list(df.index)
# # l.remove("X_PCA")
# # l = ['X_PCA'] + l
# # df = df.loc[l]


# gs_kw = dict(width_ratios=[1, 1, 1, 6])
# fig, axes = plt.subplot_mosaic([[0, 1, 2, 3]], gridspec_kw=gs_kw, figsize=(10, 6))

# mean_metrics_batch = df.loc[:, metrics_batch].mean(1)
# rank = (1 - mean_metrics_batch).rank()
# axes[1].barh(
#     y=list(range(df.shape[0])),
#     width=mean_metrics_batch,
#     color=list(
#         map(
#             lambda x: metric_batch_colormap(1 - x),
#             (rank - rank.min()) / (rank.max() - rank.min()),
#         )
#     ),
# )


# mean_metrics_bio = df.loc[:, metrics_bio].mean(1)
# rank = (1 - mean_metrics_bio).rank()
# axes[2].barh(
#     y=list(range(df.shape[0])),
#     width=mean_metrics_bio,
#     color=list(
#         map(
#             lambda x: metric_bio_colormap(1 - x),
#             (rank - rank.min()) / (rank.max() - rank.min()),
#         )
#     ),
# )

# mean_metrics_overall = df.mean(1)
# rank = (1 - mean_metrics_overall).rank()
# axes[0].barh(
#     y=list(range(df.shape[0])),
#     width=mean_metrics_overall,
#     color=list(
#         map(
#             lambda x: metrics_overall_colormap(1 - x),
#             (rank - rank.min()) / (rank.max() - rank.min()),
#         )
#     ),
# )


# for i in range(df.shape[1]):
#     rank = (1 - df.iloc[:, i]).rank()
#     if df.columns[i] in metrics_batch:
#         c = list(
#             map(
#                 lambda x: metric_batch_colormap(1 - x),
#                 (rank - rank.min()) / (rank.max() - rank.min()),
#             )
#         )
#     else:
#         c = list(
#             map(
#                 lambda x: metric_bio_colormap(1 - x),
#                 (rank - rank.min()) / (rank.max() - rank.min()),
#             )
#         )
#     s = df.iloc[:, i]
#     s = reject_outliers(s)
#     s = (df.iloc[:, i] - s.min()) / (s.max() - s.min())
#     axes[3].scatter(
#         y=list(range(df.shape[0])),
#         x=[i] * df.shape[0],
#         s=np.array(s) * 400,
#         lw=0.1,
#         edgecolor="black",
#         c=c,
#     )
# # axes[3].set_yticks(range(df.shape[0]))
# # axes[3].set_yticklabels(df.index)
# axes[3].set_xticks(range(df.shape[1]))
# axes[3].set_xticklabels(df.columns, rotation=90)
# axes[3].set_title("Extended Data Fig 4")
# #fig.savefig("./bm_demo.pdf")

In [2]:
da1 = pd.read_csv('./processed/bm/benchmark_3.csv', index_col=0)
da1 = da1.iloc[:3,:]
da2 = pd.read_csv('./processed/bm/benchmark_4.csv', index_col=0)
da2 = da2.iloc[:4,:]
da3 = pd.read_csv('./processed/bm/benchmark_5.csv', index_col=0)
da3 = da3.iloc[:1,:]
data = pd.concat([da1, da2, da3])
data

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
multi_spectral,0.41318965,0.4094629769764192,0.13876292333430443,0.596095860004425,0.9999999724901639,0.8002008,0.014734914302825928,0.2350502465527298,0.6306027208268224,0,0.33611774033031105,0.5115022764774444,0.441348462018591
multi_spectral_harmony,0.3753964,0.3769816546535219,0.15862530752648815,0.5744519233703613,0.9999999541502732,0.8100377,0.02304217338562012,0.31263474690889675,0.6040297295341777,0.9020331619493859,0.5303554968595529,0.49709104807814464,0.5103968275907079
harmony_multi_spectral,0.41999224,0.4117279782546773,0.18303735848593589,0.5741055607795715,0.9999999724901639,0.771402,0.013194782733917236,0.2067990828878777,0.6240770200950052,0,0.3230945774195441,0.5177726216587012,0.43990140396303834
wnn_m_umap,0.41721728,0.3864706507362712,0.12525509124649972,0.5744092091917992,0.9998954809629,0.5019624,0.025457546710968018,0.09390673705403223,0.49736659661094273,0,0.22373866074010557,0.5006495433156929,0.3898851902854579
wnn_h_m_umap,0.21579732,0.3742605004965026,0.10774991462195921,0.5423513613641262,0.9957902064690223,0.4123106,0.06432764053344726,0.3034406623915094,0.5177163182484906,0.00026065380956769344,0.2596111750527553,0.44718986059197763,0.37215838637628873
mtv,0.37128544,0.3916238773962591,0.1825420719699124,0.5574501007795334,0.9978420367607703,0.73703855,0.032737362384796145,0.2677338240611117,0.6597037980908469,0.4651471688505616,0.4324721412296789,0.5001487050888146,0.4730780795451603
uinmf,0.3525152,0.3485508114508969,0.2148940105998974,0.5493008084595203,0.9955439017369196,0.55939305,0.04564267635345459,0.2044600829488745,0.4451848833290941,0.622279974992854,0.37539213318214304,0.4921609446174003,0.44545342004329735
X_mofa,0.35293552,0.38735239382116915,0.19961987506327583,0.5621697157621384,0.9999999358103826,0.70584476,0.01755500555038452,0.20192927198570376,0.5264519207020231,0.9999996543963835,0.4903561225151192,0.5004154886503379,0.4963917421962504

In [4]:
data.sort_values(by='Total', ascending=False, inplace=True)
data

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
multi_spectral_harmony,0.3753964,0.3769816546535219,0.15862530752648815,0.5744519233703613,0.9999999541502732,0.8100377,0.02304217338562012,0.31263474690889675,0.6040297295341777,0.9020331619493859,0.5303554968595529,0.49709104807814464,0.5103968275907079
X_mofa,0.35293552,0.38735239382116915,0.19961987506327583,0.5621697157621384,0.9999999358103826,0.70584476,0.01755500555038452,0.20192927198570376,0.5264519207020231,0.9999996543963835,0.4903561225151192,0.5004154886503379,0.4963917421962504
mtv,0.37128544,0.3916238773962591,0.1825420719699124,0.5574501007795334,0.9978420367607703,0.73703855,0.032737362384796145,0.2677338240611117,0.6597037980908469,0.4651471688505616,0.4324721412296789,0.5001487050888146,0.4730780795451603
uinmf,0.3525152,0.3485508114508969,0.2148940105998974,0.5493008084595203,0.9955439017369196,0.55939305,0.04564267635345459,0.2044600829488745,0.4451848833290941,0.622279974992854,0.37539213318214304,0.4921609446174003,0.44545342004329735
multi_spectral,0.41318965,0.4094629769764192,0.13876292333430443,0.596095860004425,0.9999999724901639,0.8002008,0.014734914302825928,0.2350502465527298,0.6306027208268224,0,0.33611774033031105,0.5115022764774444,0.441348462018591
harmony_multi_spectral,0.41999224,0.4117279782546773,0.18303735848593589,0.5741055607795715,0.9999999724901639,0.771402,0.013194782733917236,0.2067990828878777,0.6240770200950052,0,0.3230945774195441,0.5177726216587012,0.43990140396303834
wnn_m_umap,0.41721728,0.3864706507362712,0.12525509124649972,0.5744092091917992,0.9998954809629,0.5019624,0.025457546710968018,0.09390673705403223,0.49736659661094273,0,0.22373866074010557,0.5006495433156929,0.3898851902854579
wnn_h_m_umap,0.21579732,0.3742605004965026,0.10774991462195921,0.5423513613641262,0.9957902064690223,0.4123106,0.06432764053344726,0.3034406623915094,0.5177163182484906,0.00026065380956769344,0.2596111750527553,0.44718986059197763,0.37215838637628873

In [5]:
data[['Total','Batch correction','Bio conservation']]

,Total,Batch correction,Bio conservation
Embedding,,,
multi_spectral_harmony,0.5103968275907079,0.5303554968595529,0.49709104807814464
X_mofa,0.4963917421962504,0.4903561225151192,0.5004154886503379
mtv,0.4730780795451603,0.4324721412296789,0.5001487050888146
uinmf,0.44545342004329735,0.37539213318214304,0.4921609446174003
multi_spectral,0.441348462018591,0.33611774033031105,0.5115022764774444
harmony_multi_spectral,0.43990140396303834,0.3230945774195441,0.5177726216587012
wnn_m_umap,0.3898851902854579,0.22373866074010557,0.5006495433156929
wnn_h_m_umap,0.37215838637628873,0.2596111750527553,0.44718986059197763

In [16]:
dat = pd.read_csv('./processed/bm/benchmark_2_4.csv', index_col=0)
dat = dat.iloc[:1,:]
dat

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
atac_spectral_harmony,0.40078947,0.3155589515372473,0.1289119346102535,0.5564023070037365,0.998926960504972,0.79430145,0.01437654733657837,0.14820846058494977,0.5729776598900319,0.9733702260571415,0.5006468688242469,0.4801179246273447,0.4883295023061056

In [17]:
data = pd.read_csv('./processed/bm/benchmark_2.csv', index_col=0)
data = data.iloc[:3,:]
data

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
atac_lsi,0.48963234,0.26471520372792706,0.02250865477946884,0.4795838613063097,0.9916020173292893,0.7454763,0.02976559638977051,0.2003031071737021,0.4323632078428429,0.5361920743279232,0.38882005824380206,0.4496084150856882,0.42529307234893376
atac_lsi_harmony,0.4867871,0.16755567019818457,0.036469608146593516,0.4777424428611994,0.9786141102130597,0.74256355,0.0373004150390625,0.35120848588844217,0.2561328783476425,0.9935839053460096,0.4761578460650089,0.42943378839722596,0.4481234114643391
atac_spectral,0.4068853,0.3511528396511818,0.10120459228766025,0.5416127406060696,0.9989867210388184,0.74737453,0.015846378803253174,0.13555346298606893,0.6089418281024244,0,0.301543240899736,0.4799684379380137,0.4085983591227026

In [18]:
data = pd.concat([data, dat])
data

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
atac_lsi,0.48963234,0.26471520372792706,0.02250865477946884,0.4795838613063097,0.9916020173292893,0.7454763,0.02976559638977051,0.2003031071737021,0.4323632078428429,0.5361920743279232,0.38882005824380206,0.4496084150856882,0.42529307234893376
atac_lsi_harmony,0.4867871,0.16755567019818457,0.036469608146593516,0.4777424428611994,0.9786141102130597,0.74256355,0.0373004150390625,0.35120848588844217,0.2561328783476425,0.9935839053460096,0.4761578460650089,0.42943378839722596,0.4481234114643391
atac_spectral,0.4068853,0.3511528396511818,0.10120459228766025,0.5416127406060696,0.9989867210388184,0.74737453,0.015846378803253174,0.13555346298606893,0.6089418281024244,0,0.301543240899736,0.4799684379380137,0.4085983591227026
atac_spectral_harmony,0.40078947,0.3155589515372473,0.1289119346102535,0.5564023070037365,0.998926960504972,0.79430145,0.01437654733657837,0.14820846058494977,0.5729776598900319,0.9733702260571415,0.5006468688242469,0.4801179246273447,0.4883295023061056

In [19]:
data = data.astype('float')

In [29]:
data.sort_values(by='Total', ascending=True, inplace=True)
data

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
Embedding,,,,,,,,,,,,,
atac_spectral,0.068614,1.000000,0.739601,0.811981,1.000000,0.092988,0.064118,0.000000,1.000000,0.000000,0.301543,0.479968,0.408598
atac_lsi,1.000000,0.529200,0.000000,0.023410,0.637518,0.056298,0.671311,0.300246,0.499506,0.539655,0.388820,0.449608,0.425293
atac_lsi_harmony,0.967974,0.000000,0.131208,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.476158,0.429434,0.448123
atac_spectral_harmony,0.000000,0.806131,1.000000,1.000000,0.997067,1.000000,0.000000,0.058682,0.898063,0.979656,0.500647,0.480118,0.488330

In [30]:
df = data.iloc[:8,:10]
df

,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison
Embedding,,,,,,,,,,
atac_spectral,0.068614,1.000000,0.739601,0.811981,1.000000,0.092988,0.064118,0.000000,1.000000,0.000000
atac_lsi,1.000000,0.529200,0.000000,0.023410,0.637518,0.056298,0.671311,0.300246,0.499506,0.539655
atac_lsi_harmony,0.967974,0.000000,0.131208,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000
atac_spectral_harmony,0.000000,0.806131,1.000000,1.000000,0.997067,1.000000,0.000000,0.058682,0.898063,0.979656

In [31]:
df.columns

Index(['Isolated labels', 'KMeans NMI', 'KMeans ARI', 'Silhouette label',
       'cLISI', 'Silhouette batch', 'iLISI', 'KBET', 'Graph connectivity',
       'PCR comparison'],
      dtype='object')

In [ ]:
for i in range(df.shape[1]):
    arr = df.iloc[:, i].to_numpy().flatten()
    df.iloc[:, i] = (arr - arr.min()) / (arr.max() - arr.min())

metrics_bio = [
    'Isolated labels', 'KMeans NMI', 'KMeans ARI', 'Silhouette label',
       'cLISI'
]

metrics_batch = [
    'Silhouette batch', 'iLISI', 'KBET', 'Graph connectivity',
       'PCR comparison'
]

df = df[df.index != "X_PCA"]

df = df.loc[:, metrics_batch + metrics_bio]
df = df.iloc[::-1]
l = list(df.index)
# l.remove("X_PCA")
# l = ['X_PCA'] + l
# df = df.loc[l]


gs_kw = dict(width_ratios=[1, 1, 1, 6])
fig, axes = plt.subplot_mosaic([[0, 1, 2, 3]], gridspec_kw=gs_kw, figsize=(10, 6))

mean_metrics_batch = data['Batch correction']
rank = (1 - mean_metrics_batch).rank()
axes[1].barh(
    y=list(range(df.shape[0])),
    width=mean_metrics_batch,
    color=list(
        map(
            lambda x: metric_batch_colormap(1 - x),
            (rank - rank.min()) / (rank.max() - rank.min()),
        )
    ),
)


mean_metrics_bio = data['Bio conservation']
rank = (1 - mean_metrics_bio).rank()
axes[2].barh(
    y=list(range(df.shape[0])),
    width=mean_metrics_bio,
    color=list(
        map(
            lambda x: metric_bio_colormap(1 - x),
            (rank - rank.min()) / (rank.max() - rank.min()),
        )
    ),
)

mean_metrics_overall = data['Total']
rank = (1 - mean_metrics_overall).rank()
axes[0].barh(
    y=list(range(df.shape[0])),
    width=mean_metrics_overall,
    color=list(
        map(
            lambda x: metrics_overall_colormap(1 - x),
            (rank - rank.min()) / (rank.max() - rank.min()),
        )
    ),
)


for i in range(df.shape[1]):
    rank = (1 - df.iloc[:, i]).rank()
    if df.columns[i] in metrics_batch:
        c = list(
            map(
                lambda x: metric_batch_colormap(1 - x),
                (rank - rank.min()) / (rank.max() - rank.min()),
            )
        )
    else:
        c = list(
            map(
                lambda x: metric_bio_colormap(1 - x),
                (rank - rank.min()) / (rank.max() - rank.min()),
            )
        )
    s = df.iloc[:, i]
    s = reject_outliers(s)
    s = (df.iloc[:, i] - s.min()) / (s.max() - s.min())
    axes[3].scatter(
        y=list(range(df.shape[0])),
        x=[i] * df.shape[0],
        s=np.array(s) * 400,
        lw=0.1,
        edgecolor="black",
        c=c,
    )
# axes[3].set_yticks(range(df.shape[0]))
axes[3].set_yticklabels(df.index)
axes[3].set_xticks(range(df.shape[1]))
axes[3].set_xticklabels(df.columns, rotation=90)
fig.savefig("./bm_2_4.pdf")

In [48]:
2113504-874480+53718

1292742

In [49]:
1292742+349124

1641866

## Bar

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np


colors = [
    "#4D004A",  
    "#88419D",  
    "#8C96C6",  
    "#BFD3E6",  
    "#CEF5FD",  
]

metric_batch_colormap = mcolors.LinearSegmentedColormap.from_list("custom_colormap", colors)

fig, ax = plt.subplots(figsize=(6, 1))  
fig.subplots_adjust(bottom=0.5)

cbar = fig.colorbar(
    plt.cm.ScalarMappable(cmap=metric_batch_colormap),
    cax=ax,
    orientation="horizontal",
)

cbar.set_label("Custom Colormap Bar")
plt.savefig("bar1.pdf", format="pdf", bbox_inches="tight")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

colors = [
        "#49006A",
        "#AE007E",
        "#F768A1",
        "#FCC5C0",
        "#FFE9DE",
    ]

metric_batch_colormap = mcolors.LinearSegmentedColormap.from_list("custom_colormap", colors)

fig, ax = plt.subplots(figsize=(6, 1))  
fig.subplots_adjust(bottom=0.5)

cbar = fig.colorbar(
    plt.cm.ScalarMappable(cmap=metric_batch_colormap),
    cax=ax,
    orientation="horizontal",
)

cbar.set_label("Custom Colormap Bar")
plt.savefig("bar2.pdf", format="pdf", bbox_inches="tight")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np


colors = [
        "#0A1D58",
        "#235FA8",
        "#40B6C4",
        "#C7E9B4",
        "#FDFFAB",
    ]

metric_batch_colormap = mcolors.LinearSegmentedColormap.from_list("custom_colormap", colors)

fig, ax = plt.subplots(figsize=(6, 1))  
fig.subplots_adjust(bottom=0.5)

cbar = fig.colorbar(
    plt.cm.ScalarMappable(cmap=metric_batch_colormap),
    cax=ax,
    orientation="horizontal",
)

cbar.set_label("Custom Colormap Bar")
plt.savefig("bar3.pdf", format="pdf", bbox_inches="tight")
plt.show()

# Peak evaluate

In [ ]:
import matplotlib.pyplot as plt

values = [1063878, 1154611, 1567527]
categories = ["Category 1", "Category 2", "Category 3"]

plt.figure(figsize=(8, 5))
plt.barh(categories, values, color=['#1f77b4', '#ff7f0e', '#2ca02c'])

plt.xlabel("Values")
plt.ylabel("Categories")
plt.title("Horizontal Bar Chart")

for index, value in enumerate(values):
    plt.text(value + 50000, index, str(value), va='center')

plt.tight_layout()

plt.savefig("horizontal_bar_chart.pdf", format="pdf")
plt.show()

In [ ]:
import matplotlib.pyplot as plt

# Data
values = [56.7, 69.2, 91.6]
categories = ["Category 1", "Category 2", "Category 3"]

# Create horizontal bar chart
plt.figure(figsize=(8, 5))
plt.barh(categories, values, color=['#1f77b4', '#ff7f0e', '#2ca02c'])

# Add labels and title
plt.xlabel("Percentage")
plt.ylabel("Categories")
plt.title("Horizontal Bar Chart")

# Add value annotations
for index, value in enumerate(values):
    plt.text(value + 1, index, f"{value}%", va='center')

# Save as PDF
plt.tight_layout()
plt.savefig("horizontal_bar_chart_percentage.pdf", format="pdf")
plt.show()

# Sequencing technology

In [ ]:
import matplotlib.pyplot as plt

labels = ["10x multiome", "TEA-seq", "DOGMA-seq", "ReDeeM", "NEAT-seq"]
sizes = [144, 23, 16, 16, 2]

total = sum(sizes)
percentages = [f"{size} ({size / total * 100:.1f}%)" for size in sizes]

plt.figure(figsize=(8, 8))
wedges, texts, autotexts = plt.pie(
    sizes, labels=labels, autopct=lambda p: f"{p:.1f}%" if p > 0 else "",
    colors=plt.cm.Paired.colors, startangle=140, textprops={'fontsize': 12}
)

plt.legend(wedges, [f"{label}: {percentage}" for label, percentage in zip(labels, percentages)],
           title="Methods", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1), fontsize=10)

plt.title("Distribution of Methods", fontsize=16)

plt.tight_layout()
plt.savefig("tech_sample.pdf", format="pdf")
plt.show()

In [ ]:
import matplotlib.pyplot as plt

labels = ["10x multiome", "TEA-seq", "DOGMA-seq", "ReDeeM", "NEAT-seq"]
sizes = [962970, 362002, 178607, 129830, 8457]  # 数量
total = sum(sizes)

percentages = [f"{size} ({size / total * 100:.1f}%)" for size in sizes]

plt.figure(figsize=(8, 8))
wedges, texts, autotexts = plt.pie(
    sizes, labels=labels, autopct=lambda p: f"{p:.1f}%" if p > 0 else "",
    colors=plt.cm.Paired.colors, startangle=140, textprops={'fontsize': 12}
)

plt.legend(wedges, [f"{label}: {percentage}" for label, percentage in zip(labels, percentages)],
           title="Methods", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1), fontsize=10)

plt.title("Distribution of Methods", fontsize=16)

plt.tight_layout()
plt.savefig("tech_cell.pdf", format="pdf")
plt.show()