In [1]:
import scanpy as sc
import pandas as pd
import anndata as ad

# Add various information to the original object

In [2]:
data = sc.read_h5ad('../6_integrate/processed/adata_rna.h5ad')
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType'

In [3]:
data.obs.columns = ['dataset', 'barcode', 'sample', 'cellType_raw']

In [4]:
data.obs

,dataset,barcode,sample,cellType_raw
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM
...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable

## cell information

In [5]:
cell = pd.read_csv('../6_ann/origin/cellname.csv')
cell

           cellType       level_1       level_2                   level_3
0            01_HSC       HSC/MPP       HSC/MPP                   HSC/MPP
1    02_Early.Eryth       Myeloid     Erythroid           Early erythroid
2     03_Late.Eryth       Myeloid     Erythroid            Late erythroid
3     04_Early.Baso       Myeloid  Granulocytes              Granulocytes
4       05_CMP.LMPP       HSC/MPP       HSC/MPP                       CMP
..              ...           ...           ...                       ...
139            Treg      Lymphoid       T cells        Regulatory T cells
140          Treg_1      Lymphoid       T cells        Regulatory T cells
141          Treg_2      Lymphoid       T cells        Regulatory T cells
142           Uncom      Lymphoid       T cells  Tcm/Naive helper T cells
143    notAvailable  notAvailable  notAvailable              notAvailable

[144 rows x 4 columns]

In [6]:
all = pd.merge(data.obs, cell, left_on='cellType_raw', right_on='cellType', how='left')
all.index = data.obs_names.tolist()
all

,dataset,barcode,sample,cellType_raw,cellType,level_1,level_2,level_3
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Treg,Lymphoid,T cells,Regulatory T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Treg,Lymphoid,T cells,Regulatory T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Th17,Lymphoid,T cells,Type 17 helper T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Th1,Lymphoid,T cells,Type 1 helper T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,TCM,Lymphoid,T cells,Tcm/Naive helper T cells
...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,notAvailable

In [7]:
data.obs['cellType_raw_level1'] = all['level_1'].tolist()
data.obs['cellType_raw_level2'] = all['level_2'].tolist()
data.obs['cellType_raw_level3'] = all['level_3'].tolist()

In [8]:
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3'

In [9]:
cell = pd.read_csv('../6_ann/all_method8.csv', index_col=0)
cell

,scarch,actinn,celltypist,scmap,singcellnet,scpred,singler,chetah
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Neutrophils,Regulatory T cells,Regulatory T cells,unassigned,Tcm/Naive helper T cells,Regulatory T cells,Tem/Effector helper T cells PD1+,Treg(diff)
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Neutrophils,Treg(diff),Tem/Effector helper T cells,unassigned,Regulatory T cells,Regulatory T cells,ILC2,Early lymphoid/T lymphoid
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Neutrophils,T cells,CD16- NK cells,Neutrophils,Tcm/Naive helper T cells,Helper T cells,ILC2,Treg(diff)
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,Neutrophils,Helper T cells,Helper T cells,Megakaryocyte precursor,Treg(diff)
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,Type 17 helper T cells,Tcm/Naive helper T cells,Helper T cells,Tem/Effector helper T cells PD1+,Treg(diff)
...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Follicular B cells,Naive B cells,Small pre-B cells,Naive B cells,Naive B cells,Memory B cells,Naive B cells,Unassigned
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Myelocytes,Transitional B cells,Small pre-B cells,NK cells,CD16+ NK cells,Naive B cells,Immature B cells,Immature B cells
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Memory B cells,Memory B cells,Memory B cells,Memory B cells,Memory B cells,Memory B cells,Memory B cells,B cells
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Myelocytes,NK cells,Tem/Temra cytotoxic T cells,NK cells,Cytotoxic T cells,Cytotoxic T cells,Cytotoxic T cells,Megakaryocytes/platelets
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,pDC,Memory B cells,pDC,pDC,pDC,pDC,pDC,Node10

In [10]:
cell.columns

Index(['scarch', 'actinn', 'celltypist', 'scmap', 'singcellnet', 'scpred',
       'singler', 'chetah'],
      dtype='object')

In [11]:
cell.columns = ['cellType_scarch_level3', 
                'cellType_actinn_level3', 
                'cellType_celltypist_level3', 
                'cellType_scmap_level3', 
                'cellType_singlecellnet_level3', 
                'cellType_scpred_level3', 
                'cellType_singler_level3',
                'cellType_chetah_level3']

In [12]:
data.obs

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells
...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable

In [13]:
all = pd.concat([data.obs, cell], axis=1)
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,cellType_scmap_level3,cellType_singlecellnet_level3,cellType_scpred_level3,cellType_singler_level3,cellType_chetah_level3
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,unassigned,Tcm/Naive helper T cells,Regulatory T cells,Tem/Effector helper T cells PD1+,Treg(diff)
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,unassigned,Regulatory T cells,Regulatory T cells,ILC2,Early lymphoid/T lymphoid
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,Neutrophils,Tcm/Naive helper T cells,Helper T cells,ILC2,Treg(diff)
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,Neutrophils,Helper T cells,Helper T cells,Megakaryocyte precursor,Treg(diff)
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,Type 17 helper T cells,Tcm/Naive helper T cells,Helper T cells,Tem/Effector helper T cells PD1+,Treg(diff)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Follicular B cells,Naive B cells,Small pre-B cells,Naive B cells,Naive B cells,Memory B cells,Naive B cells,Unassigned
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Myelocytes,Transitional B cells,Small pre-B cells,NK cells,CD16+ NK cells,Naive B cells,Immature B cells,Immature B cells
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Memory B cells,Memory B cells,Memory B cells,Memory B cells,Memory B cells,Memory B cells,Memory B cells,B cells
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Myelocytes,NK cells,Tem/Temra cytotoxic T cells,NK cells,Cytotoxic T cells,Cytotoxic T cells,Cytotoxic T cells,Megakaryocytes/platelets
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,pDC,Memory B cells,pDC,pDC,pDC,pDC,pDC,Node10

In [14]:
data.obs = all

In [15]:
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3'

In [16]:
cell = pd.read_csv('../6_ann/all_method8_level2.csv', index_col=0)
cell

,scarch,actinn,celltypist,scmap,singcellnet,scpred,singler,chetah
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Granulocytes,T cells,T cells,unassigned,T cells,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Granulocytes,T cells,T cells,unassigned,T cells,T cells,ILC,HSC/MPP
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Granulocytes,T cells,ILC,Granulocytes,T cells,T cells,ILC,T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Granulocytes,ILC,T cells,Granulocytes,T cells,T cells,Megakaryocyte precursor,T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Granulocytes,T cells,T cells,T cells,T cells,T cells,T cells,T cells
...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,B cells,B cells,B-cell lineage,B cells,B cells,B cells,B cells,Unassigned
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Myelocytes,B cells,B-cell lineage,ILC,ILC,B cells,B cells,B cells
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,B cells,B cells,B cells,B cells,B cells,B cells,B cells,B cells
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Myelocytes,ILC,T cells,ILC,T cells,T cells,T cells,Megakaryocytes/platelets
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,pDC,B cells,pDC,pDC,pDC,pDC,pDC,Node10

In [17]:
cell.columns = ['cellType_scarch_level2', 
                'cellType_actinn_level2', 
                'cellType_celltypist_level2', 
                'cellType_scmap_level2', 
                'cellType_singlecellnet_level2', 
                'cellType_scpred_level2', 
                'cellType_singler_level2',
                'cellType_chetah_level2']

In [18]:
all = pd.concat([data.obs, cell], axis=1)
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_singler_level3,cellType_chetah_level3,cellType_scarch_level2,cellType_actinn_level2,cellType_celltypist_level2,cellType_scmap_level2,cellType_singlecellnet_level2,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,Tem/Effector helper T cells PD1+,Treg(diff),Granulocytes,T cells,T cells,unassigned,T cells,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,ILC2,Early lymphoid/T lymphoid,Granulocytes,T cells,T cells,unassigned,T cells,T cells,ILC,HSC/MPP
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,ILC2,Treg(diff),Granulocytes,T cells,ILC,Granulocytes,T cells,T cells,ILC,T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,Megakaryocyte precursor,Treg(diff),Granulocytes,ILC,T cells,Granulocytes,T cells,T cells,Megakaryocyte precursor,T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,Tem/Effector helper T cells PD1+,Treg(diff),Granulocytes,T cells,T cells,T cells,T cells,T cells,T cells,T cells
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Follicular B cells,Naive B cells,Small pre-B cells,...,Naive B cells,Unassigned,B cells,B cells,B-cell lineage,B cells,B cells,B cells,B cells,Unassigned
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Myelocytes,Transitional B cells,Small pre-B cells,...,Immature B cells,Immature B cells,Myelocytes,B cells,B-cell lineage,ILC,ILC,B cells,B cells,B cells
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Memory B cells,Memory B cells,Memory B cells,...,Memory B cells,B cells,B cells,B cells,B cells,B cells,B cells,B cells,B cells,B cells
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Myelocytes,NK cells,Tem/Temra cytotoxic T cells,...,Cytotoxic T cells,Megakaryocytes/platelets,Myelocytes,ILC,T cells,ILC,T cells,T cells,T cells,Megakaryocytes/platelets
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,pDC,Memory B cells,pDC,...,pDC,Node10,pDC,B cells,pDC,pDC,pDC,pDC,pDC,Node10

In [19]:
data.obs = all

In [20]:
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2'

## sample information

In [21]:
sample = pd.read_csv('../6_integrate/visual/sample_all.csv')
sample

,sample,tissue,disease_name,disease,age,age_stage,sex,technology,others
0,10x_datasets_10-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN
1,10x_datasets_1-1,blood,Healthy,healthy,32.5,30_40,Male,10x multiome,NaN
2,10x_datasets_2-1,blood,Healthy,healthy,32.5,30_40,Male,10x multiome,NaN
3,10x_datasets_3-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN
4,10x_datasets_4-1,blood,Healthy,healthy,25,20_30,Female,10x multiome,NaN
...,...,...,...,...,...,...,...,...,...
191,Wimmers_Cell_2023-71_CC0594,blood,COVID-19,acute-omicron,8.6,0_1,Male,10x multiome,NaN
192,Wimmers_Cell_2023-72_CC0688,blood,COVID-19,acute-omicron,7.5,0_1,Male,10x multiome,NaN
193,Wimmers_Cell_2023-73_CC0710,blood,COVID-19,acute-omicron,6.1,0_1,Female,10x multiome,NaN
194,Wimmers_Cell_2023-74_CC0716,blood,COVID-19,acute-omicron,5.75,0_1,Female,10x multiome,NaN
195,Wimmers_Cell_2023-76_CC0829,blood,COVID-19,acute-omicron,3.8,0_1,Male,10x multiome,NaN

In [22]:
all = pd.merge(data.obs, sample, left_on='sample', right_on='sample')
all.index = data.obs_names.tolist()
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology,others
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Weng_Nature_2024_7-TTTGTGTTCGTAATCA-1,Weng_Nature_2024_7,TTTGTGTTCGTAATCA,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Follicular B cells,Naive B cells,Small pre-B cells,...,B cells,Unassigned,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN
Weng_Nature_2024_7-TTTGTTGGTAGGATTT-1,Weng_Nature_2024_7,TTTGTTGGTAGGATTT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Myelocytes,Transitional B cells,Small pre-B cells,...,B cells,B cells,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN
Weng_Nature_2024_7-TTTGTTGGTCATTACC-1,Weng_Nature_2024_7,TTTGTTGGTCATTACC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Memory B cells,Memory B cells,Memory B cells,...,B cells,B cells,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN
Weng_Nature_2024_7-TTTGTTGGTGTTAAAC-1,Weng_Nature_2024_7,TTTGTTGGTGTTAAAC,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,Myelocytes,NK cells,Tem/Temra cytotoxic T cells,...,T cells,Megakaryocytes/platelets,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN
Weng_Nature_2024_7-TTTGTTGGTTGCATCT-1,Weng_Nature_2024_7,TTTGTTGGTTGCATCT,Weng_Nature_2024_7-1,notAvailable,notAvailable,notAvailable,notAvailable,pDC,Memory B cells,pDC,...,pDC,Node10,bone marrow,Healthy,Healthy,81/85/69,notAvailable,notAvailable,ReDeeM,NaN

In [23]:
data.obs = all

In [24]:
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'others'

In [25]:
data.obs['dataset'].value_counts()

dataset
Hu_BioRxiv_2023                874480
Thomson_Nat_Immunol_2024       336485
Wimmers_Cell_2023              288211
Cheong_Cell_2023_1             197341
Oguchi_Science_2024            145485
Wei_Immuni_2023                116549
Boukhaled_Nat_Immunol_2022      86361
NeurIPS_2021                    69249
Mimitou_Nat_Biotechnol_2021     32695
Lareau_Nat_Genet_2023           29363
Weng_Nature_2024_5              28948
Swanson_Elife_2021_1            25517
Weng_Nature_2024_4              25252
Weng_Nature_2024_6              21062
Li_Nat_Biotechnol_2023          19260
Weng_Nature_2024_3              18420
Cheong_Cell_2023_2              17244
Weng_Nature_2024_2              17011
Weng_Nature_2024_1              12781
Swanson_Elife_2021_2            11796
10x_datasets_4                  11187
10x_datasets_10                 11179
10x_datasets_6                  11112
10x_datasets_8                  11084
10x_datasets_1                   9665
10x_datasets_2                   9341
Chen_Nat_Methods_2022            8457
Weng_Nature_2024_7               6356
10x_datasets_5                   2791
10x_datasets_7                   2777
10x_datasets_3                   2587
10x_datasets_9                   2582
Name: count, dtype: int64

# Split datasets

## rna

In [26]:
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'others'

In [27]:
del data.obs['others']

In [28]:
data

AnnData object with n_obs × n_vars = 2462628 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [29]:
data.write_h5ad('./processed/rna/raw/data.h5ad')

In [34]:
dat = data[data.obs['dataset'] != 'Hu_BioRxiv_2023']
dat

View of AnnData object with n_obs × n_vars = 1588148 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [35]:
dat.write_h5ad('./processed/rna/raw/dat.h5ad')

KeyboardInterrupt:

In [32]:
hu = data[data.obs['dataset'] == 'Hu_BioRxiv_2023']
hu

View of AnnData object with n_obs × n_vars = 874480 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [33]:
hu.write_h5ad('./processed/rna/raw/hu.h5ad')

## atac

In [2]:
data = sc.read_h5ad('../6_integrate/processed/adata_atac.h5ad')
data

AnnData object with n_obs × n_vars = 2462628 × 527459
    obs: 'dataset', 'barcode', 'sample', 'cellType'

In [3]:
data.write_h5ad('./processed/data.h5ad')

In [4]:
dat = data[data.obs['dataset'] != 'Hu_BioRxiv_2023']
dat

View of AnnData object with n_obs × n_vars = 1588148 × 527459
    obs: 'dataset', 'barcode', 'sample', 'cellType'

In [5]:
dat.write_h5ad('./processed/dat.h5ad')

In [6]:
hu = data[data.obs['dataset'] == 'Hu_BioRxiv_2023']
hu

View of AnnData object with n_obs × n_vars = 874480 × 527459
    obs: 'dataset', 'barcode', 'sample', 'cellType'

In [7]:
hu.write_h5ad('./processed/hu.h5ad')

# Add new data

## rna

In [7]:
# new = sc.read_10x_mtx('../actinn/query/new/sd/')
# del new.var['gene_ids']
# df = pd.DataFrame([x.split('-') for x in new.obs_names], columns=['dataset', 'barcode', 'sample'])
# df['sample'] = df['dataset'] + '-' + df['sample']
# df.index = new.obs_names.tolist()
# new.obs = df
# new.write_h5ad('./processed/new.h5ad')

In [36]:
new = sc.read_h5ad('../8_new/processed/rna/raw/new.h5ad')
new

AnnData object with n_obs × n_vars = 53718 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_chetah_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_celltypist_level3', 'cellType_actinn_level3', 'cellType_scarch_level3', 'cellType_chetah_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_celltypist_level2', 'cellType_actinn_level2', 'cellType_scarch_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [37]:
new.obs = new.obs[['dataset', 'barcode', 'sample']]

### cell

In [38]:
meta = pd.read_csv('./processed/new_data_meta/cellType_53718.csv', index_col=0)
meta

                                                                       cellType
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H               Early erythroid
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H                      NK cells
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H                          cDCs
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H                          HSCs
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H                       T cells
...                                                                         ...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C                         NK cells
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C     Pro-inflammatory macrophages
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C                      Neutrophils
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C                             HSCs
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C                         NK cells

[53718 rows x 1 columns]

In [39]:
cell = pd.read_csv('./processed/new_data_meta/new_cell.csv')
cell

,cellType,level_1,level_2,level_3
0,MEMPs,HSC/MPP,HSC/MPP,Megakaryocyte-erythroid-mast cell progenitor
1,Early erythroid,Myeloid,Erythroid,Early erythroid
2,HSCs,HSC/MPP,HSC/MPP,HSC/MPP
3,Megakaryocytes,Myeloid,Megakaryocytes/platelets,Megakaryocytes/platelets
4,NK cells,Lymphoid,ILC,NK cells
5,B cells,Lymphoid,B cells,B cells
6,cDCs,Myeloid,DC,DC
7,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages
8,Cycling erythroid,Myeloid,Erythroid,Mid erythroid
9,Mast cells,Myeloid,Mast cells,Mast cells
10,Granulocyte progenitors,Myeloid,Granulocytes,Granulocytes
11,Late erythroid,Myeloid,Erythroid,Late erythroid
12,Kupffer cells,Myeloid,Macrophages,Kupffer cells
13,pDCs,Myeloid,pDC,pDC
14,Neutrophils,Myeloid,Granulocytes,Neutrophils
15,Stroma,others,notAvailable,notAvailable
16,T cells,Lymphoid,T cells,notAvailable

In [40]:
all = pd.merge(meta, cell, left_on='cellType', right_on='cellType', how='left')
all

                           cellType   level_1       level_2          level_3
0                   Early erythroid   Myeloid     Erythroid  Early erythroid
1                          NK cells  Lymphoid           ILC         NK cells
2                              cDCs   Myeloid            DC               DC
3                              HSCs   HSC/MPP       HSC/MPP          HSC/MPP
4                           T cells  Lymphoid       T cells     notAvailable
...                             ...       ...           ...              ...
53713                      NK cells  Lymphoid           ILC         NK cells
53714  Pro-inflammatory macrophages   Myeloid   Macrophages      Macrophages
53715                   Neutrophils   Myeloid  Granulocytes      Neutrophils
53716                          HSCs   HSC/MPP       HSC/MPP          HSC/MPP
53717                      NK cells  Lymphoid           ILC         NK cells

[53718 rows x 4 columns]

In [41]:
new.obs['cellType_raw'] = all['cellType'].tolist()
new.obs['cellType_raw_level1'] = all['level_1'].tolist()
new.obs['cellType_raw_level2'] = all['level_2'].tolist()
new.obs['cellType_raw_level3'] = all['level_3'].tolist()

In [42]:
new

AnnData object with n_obs × n_vars = 53718 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3'

In [43]:
level_3 = pd.read_csv('../6_ann/method8_level3.csv', index_col=0)
level_3

,chetah,scmap,singlecellnet,scpred,singler,celltypist,actinn,scarch
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H,Unassigned,Neutrophils,Macrophages,Early erythroid,MEMP,Early erythroid,Helper T cells,GMP
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H,Unassigned,Neutrophils,Tcm/Naive helper T cells,MEMP,MEMP,Tcm/Naive helper T cells,Helper T cells,Cycling gamma-delta T cells
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H,Unassigned,Neutrophils,Memory B cells,ETP,CD16- NK cells,CD16- NK cells,Naive B cells,Late erythroid
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H,Unassigned,Neutrophils,Helper T cells,NK cells,HSC/MPP,Classical monocytes,Helper T cells,Myelocytes
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H,Immature B cells,Neutrophils,Tcm/Naive helper T cells,Immature B cells,MEMP,Regulatory T cells,MAIT cells,Myelocytes
...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Node12,Neutrophils,Memory B cells,Helper T cells,CD16- NK cells,CD16- NK cells,Memory B cells,NK cells
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Unassigned,Neutrophils,Memory B cells,ILC,Promyelocytes,CD16+ NK cells,ILC,Neutrophils
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Unassigned,Neutrophils,Helper T cells,Promyelocytes,GMP,Tcm/Naive helper T cells,Helper T cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Unassigned,Neutrophils,Memory B cells,Tcm/Naive helper T cells,MEMP,Double-negative thymocytes,MAIT cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Promyelocytes,Neutrophils,Memory B cells,NK cells,Pre-B cells,Classical monocytes,Naive B cells,Myelocytes

In [44]:
level_3.columns = ['cellType_chetah_level3', 
                'cellType_scmap_level3', 
                'cellType_singlecellnet_level3', 
                'cellType_scpred_level3', 
                'cellType_singler_level3', 
                'cellType_celltypist_level3', 
                'cellType_actinn_level3',
               'cellType_scarch_level3']

In [45]:
all = pd.concat([new.obs, level_3], axis=1)
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_chetah_level3,cellType_scmap_level3,cellType_singlecellnet_level3,cellType_scpred_level3,cellType_singler_level3,cellType_celltypist_level3,cellType_actinn_level3,cellType_scarch_level3
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H,Marderstein_Nature_2024,AAACAGCCAGTTATCG,Marderstein_Nature_2024-TS21_4_H,Early erythroid,Myeloid,Erythroid,Early erythroid,Unassigned,Neutrophils,Macrophages,Early erythroid,MEMP,Early erythroid,Helper T cells,GMP
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H,Marderstein_Nature_2024,AAACCGAAGTCCTGAG,Marderstein_Nature_2024-TS21_4_H,NK cells,Lymphoid,ILC,NK cells,Unassigned,Neutrophils,Tcm/Naive helper T cells,MEMP,MEMP,Tcm/Naive helper T cells,Helper T cells,Cycling gamma-delta T cells
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H,Marderstein_Nature_2024,AAACGCGCAGCTAACC,Marderstein_Nature_2024-TS21_4_H,cDCs,Myeloid,DC,DC,Unassigned,Neutrophils,Memory B cells,ETP,CD16- NK cells,CD16- NK cells,Naive B cells,Late erythroid
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H,Marderstein_Nature_2024,AAACGGATCATTACTC,Marderstein_Nature_2024-TS21_4_H,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Unassigned,Neutrophils,Helper T cells,NK cells,HSC/MPP,Classical monocytes,Helper T cells,Myelocytes
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H,Marderstein_Nature_2024,AAACGGATCCTCCTAA,Marderstein_Nature_2024-TS21_4_H,T cells,Lymphoid,T cells,notAvailable,Immature B cells,Neutrophils,Tcm/Naive helper T cells,Immature B cells,MEMP,Regulatory T cells,MAIT cells,Myelocytes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Node12,Neutrophils,Memory B cells,Helper T cells,CD16- NK cells,CD16- NK cells,Memory B cells,NK cells
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Unassigned,Neutrophils,Memory B cells,ILC,Promyelocytes,CD16+ NK cells,ILC,Neutrophils
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Unassigned,Neutrophils,Helper T cells,Promyelocytes,GMP,Tcm/Naive helper T cells,Helper T cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Unassigned,Neutrophils,Memory B cells,Tcm/Naive helper T cells,MEMP,Double-negative thymocytes,MAIT cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Promyelocytes,Neutrophils,Memory B cells,NK cells,Pre-B cells,Classical monocytes,Naive B cells,Myelocytes

In [46]:
new.obs = all

In [47]:
level_2 = pd.read_csv('../6_ann/method8_level2.csv', index_col=0)
level_2

,chetah,scmap,singlecellnet,scpred,singler,celltypist,actinn,scarch
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H,Unassigned,Granulocytes,Macrophages,Erythroid,HSC/MPP,Erythroid,T cells,HSC/MPP
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H,Unassigned,Granulocytes,T cells,HSC/MPP,HSC/MPP,T cells,T cells,Cycling cells
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H,Unassigned,Granulocytes,B cells,ETP,ILC,ILC,B cells,Erythroid
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H,Unassigned,Granulocytes,T cells,ILC,HSC/MPP,Monocytes,T cells,Myelocytes
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H,B cells,Granulocytes,T cells,B cells,HSC/MPP,T cells,T cells,Myelocytes
...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Node12,Granulocytes,B cells,T cells,ILC,ILC,B cells,ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Unassigned,Granulocytes,B cells,ILC,Promyelocytes,ILC,ILC,Granulocytes
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Unassigned,Granulocytes,T cells,Promyelocytes,HSC/MPP,T cells,T cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Unassigned,Granulocytes,B cells,T cells,HSC/MPP,Double-negative thymocytes,T cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Promyelocytes,Granulocytes,B cells,ILC,B cells,Monocytes,B cells,Myelocytes

In [48]:
level_2.columns = ['cellType_chetah_level2', 
                'cellType_scmap_level2', 
                'cellType_singlecellnet_level2', 
                'cellType_scpred_level2', 
                'cellType_singler_level2', 
                'cellType_celltypist_level2', 
                'cellType_actinn_level2',
               'cellType_scarch_level2']

In [49]:
all = pd.concat([new.obs, level_2], axis=1)
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_chetah_level3,cellType_scmap_level3,cellType_singlecellnet_level3,...,cellType_actinn_level3,cellType_scarch_level3,cellType_chetah_level2,cellType_scmap_level2,cellType_singlecellnet_level2,cellType_scpred_level2,cellType_singler_level2,cellType_celltypist_level2,cellType_actinn_level2,cellType_scarch_level2
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H,Marderstein_Nature_2024,AAACAGCCAGTTATCG,Marderstein_Nature_2024-TS21_4_H,Early erythroid,Myeloid,Erythroid,Early erythroid,Unassigned,Neutrophils,Macrophages,...,Helper T cells,GMP,Unassigned,Granulocytes,Macrophages,Erythroid,HSC/MPP,Erythroid,T cells,HSC/MPP
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H,Marderstein_Nature_2024,AAACCGAAGTCCTGAG,Marderstein_Nature_2024-TS21_4_H,NK cells,Lymphoid,ILC,NK cells,Unassigned,Neutrophils,Tcm/Naive helper T cells,...,Helper T cells,Cycling gamma-delta T cells,Unassigned,Granulocytes,T cells,HSC/MPP,HSC/MPP,T cells,T cells,Cycling cells
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H,Marderstein_Nature_2024,AAACGCGCAGCTAACC,Marderstein_Nature_2024-TS21_4_H,cDCs,Myeloid,DC,DC,Unassigned,Neutrophils,Memory B cells,...,Naive B cells,Late erythroid,Unassigned,Granulocytes,B cells,ETP,ILC,ILC,B cells,Erythroid
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H,Marderstein_Nature_2024,AAACGGATCATTACTC,Marderstein_Nature_2024-TS21_4_H,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Unassigned,Neutrophils,Helper T cells,...,Helper T cells,Myelocytes,Unassigned,Granulocytes,T cells,ILC,HSC/MPP,Monocytes,T cells,Myelocytes
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H,Marderstein_Nature_2024,AAACGGATCCTCCTAA,Marderstein_Nature_2024-TS21_4_H,T cells,Lymphoid,T cells,notAvailable,Immature B cells,Neutrophils,Tcm/Naive helper T cells,...,MAIT cells,Myelocytes,B cells,Granulocytes,T cells,B cells,HSC/MPP,T cells,T cells,Myelocytes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Node12,Neutrophils,Memory B cells,...,Memory B cells,NK cells,Node12,Granulocytes,B cells,T cells,ILC,ILC,B cells,ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Unassigned,Neutrophils,Memory B cells,...,ILC,Neutrophils,Unassigned,Granulocytes,B cells,ILC,Promyelocytes,ILC,ILC,Granulocytes
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Unassigned,Neutrophils,Helper T cells,...,Helper T cells,Myelocytes,Unassigned,Granulocytes,T cells,Promyelocytes,HSC/MPP,T cells,T cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Unassigned,Neutrophils,Memory B cells,...,MAIT cells,Myelocytes,Unassigned,Granulocytes,B cells,T cells,HSC/MPP,Double-negative thymocytes,T cells,Myelocytes
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Promyelocytes,Neutrophils,Memory B cells,...,Naive B cells,Myelocytes,Promyelocytes,Granulocytes,B cells,ILC,B cells,Monocytes,B cells,Myelocytes

In [50]:
new.obs = all

### sample

In [51]:
sample = pd.read_csv('./processed/new_data_meta/new_sample.csv')
sample

,sample,tissue,disease_name,disease,age,age_stage,sex,technology,others
0,Marderstein_Nature_2024-TS21_4_I,fetal liver,Down syndrome,Ts21,13 pcw,0_1,notAvailable,10x multiome,NaN
1,Marderstein_Nature_2024-TS21_4_H,fetal liver,Down syndrome,Ts22,13 pcw,0_1,notAvailable,10x multiome,NaN
2,Marderstein_Nature_2024-TS21_16_B,fetal liver,Down syndrome,Ts23,13 pcw,0_1,notAvailable,10x multiome,NaN
3,Marderstein_Nature_2024-TS21_16_A,fetal liver,Down syndrome,Ts24,13 pcw,0_1,notAvailable,10x multiome,NaN
4,Marderstein_Nature_2024-TS21_11_G,fetal liver,Down syndrome,Ts25,14 pcw,0_1,notAvailable,10x multiome,NaN
5,Marderstein_Nature_2024-TS21_11_F,fetal liver,Down syndrome,Ts26,14 pcw,0_1,notAvailable,10x multiome,NaN
6,Marderstein_Nature_2024-H_7_C,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
7,Marderstein_Nature_2024-H_7_B,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
8,Marderstein_Nature_2024-H_7_A,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
9,Marderstein_Nature_2024-H_6_A,fetal liver,Healthy,Healthy,12 pcw,0_1,notAvailable,10x multiome,NaN
10,Marderstein_Nature_2024-H_5_B,fetal liver,Healthy,Healthy,12 pcw,0_1,notAvailable,10x multiome,NaN
11,Marderstein_Nature_2024-H_5_A,fetal liver,Healthy,Healthy,12 pcw,0_1,notAvailable,10x multiome,NaN

In [52]:
all = pd.merge(new.obs, sample, left_on='sample', right_on='sample')
all.index = new.obs_names.tolist()
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_chetah_level3,cellType_scmap_level3,cellType_singlecellnet_level3,...,cellType_actinn_level2,cellType_scarch_level2,tissue,disease_name,disease,age,age_stage,sex,technology,others
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H,Marderstein_Nature_2024,AAACAGCCAGTTATCG,Marderstein_Nature_2024-TS21_4_H,Early erythroid,Myeloid,Erythroid,Early erythroid,Unassigned,Neutrophils,Macrophages,...,T cells,HSC/MPP,fetal liver,Down syndrome,Ts22,13 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H,Marderstein_Nature_2024,AAACCGAAGTCCTGAG,Marderstein_Nature_2024-TS21_4_H,NK cells,Lymphoid,ILC,NK cells,Unassigned,Neutrophils,Tcm/Naive helper T cells,...,T cells,Cycling cells,fetal liver,Down syndrome,Ts22,13 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H,Marderstein_Nature_2024,AAACGCGCAGCTAACC,Marderstein_Nature_2024-TS21_4_H,cDCs,Myeloid,DC,DC,Unassigned,Neutrophils,Memory B cells,...,B cells,Erythroid,fetal liver,Down syndrome,Ts22,13 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H,Marderstein_Nature_2024,AAACGGATCATTACTC,Marderstein_Nature_2024-TS21_4_H,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Unassigned,Neutrophils,Helper T cells,...,T cells,Myelocytes,fetal liver,Down syndrome,Ts22,13 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H,Marderstein_Nature_2024,AAACGGATCCTCCTAA,Marderstein_Nature_2024-TS21_4_H,T cells,Lymphoid,T cells,notAvailable,Immature B cells,Neutrophils,Tcm/Naive helper T cells,...,T cells,Myelocytes,fetal liver,Down syndrome,Ts22,13 pcw,0_1,notAvailable,10x multiome,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Node12,Neutrophils,Memory B cells,...,B cells,ILC,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Unassigned,Neutrophils,Memory B cells,...,ILC,Granulocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Unassigned,Neutrophils,Helper T cells,...,T cells,Myelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Unassigned,Neutrophils,Memory B cells,...,T cells,Myelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Promyelocytes,Neutrophils,Memory B cells,...,B cells,Myelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome,NaN

In [53]:
new.obs = all

In [54]:
del new.obs['others']

In [55]:
new

AnnData object with n_obs × n_vars = 53718 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_chetah_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_celltypist_level3', 'cellType_actinn_level3', 'cellType_scarch_level3', 'cellType_chetah_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_celltypist_level2', 'cellType_actinn_level2', 'cellType_scarch_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [56]:
new.write_h5ad('./processed/rna/raw/new.h5ad')

### concat data

In [3]:
data = sc.read_h5ad('./processed/rna/raw/data.h5ad')
dat = data[data.obs['dataset'] != 'Hu_BioRxiv_2023']
dat

View of AnnData object with n_obs × n_vars = 1588148 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [4]:
new = sc.read_h5ad('./processed/rna/raw/new.h5ad')
new

AnnData object with n_obs × n_vars = 53718 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_chetah_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_celltypist_level3', 'cellType_actinn_level3', 'cellType_scarch_level3', 'cellType_chetah_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_celltypist_level2', 'cellType_actinn_level2', 'cellType_scarch_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [5]:
new.obs = new.obs[dat.obs.columns.tolist()]

In [57]:
data_new = ad.concat([dat, new])
data_new

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [58]:
data_new.write_h5ad('./processed/rna/data_new.h5ad')

## atac

In [2]:
new_mat = sc.read_mtx('/pool1/qiaolibo/R_Project/peak_gene/Marderstein_Nature_2024/processed/filter_matrix/atac.mtx')
new_mat = new_mat.T

AnnData object with n_obs × n_vars = 527459 × 53718

In [4]:
new_cell = pd.read_csv('../actinn/query/new/raw/cell.csv', index_col=0)
new_cell

                                                 cell_id
1      Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H
2      Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H
3      Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H
4      Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H
5      Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H
...                                                  ...
53714     Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C
53715     Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C
53716     Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C
53717     Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C
53718     Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C

[53718 rows x 1 columns]

In [6]:
data = sc.read_h5ad('./processed/dat.h5ad')

In [7]:
new_mat.obs_names = new_cell['cell_id'].tolist()
new_mat.var_names = data.var_names.tolist()

In [8]:
df = pd.DataFrame([x.split('-') for x in new_mat.obs_names], columns=['dataset', 'barcode', 'sample'])
df['sample'] = df['dataset'] + '-' + df['sample']
df.index = new_mat.obs_names.tolist()
df

,dataset,barcode,sample
Marderstein_Nature_2024-AAACAGCCAGTTATCG-TS21_4_H,Marderstein_Nature_2024,AAACAGCCAGTTATCG,Marderstein_Nature_2024-TS21_4_H
Marderstein_Nature_2024-AAACCGAAGTCCTGAG-TS21_4_H,Marderstein_Nature_2024,AAACCGAAGTCCTGAG,Marderstein_Nature_2024-TS21_4_H
Marderstein_Nature_2024-AAACGCGCAGCTAACC-TS21_4_H,Marderstein_Nature_2024,AAACGCGCAGCTAACC,Marderstein_Nature_2024-TS21_4_H
Marderstein_Nature_2024-AAACGGATCATTACTC-TS21_4_H,Marderstein_Nature_2024,AAACGGATCATTACTC,Marderstein_Nature_2024-TS21_4_H
Marderstein_Nature_2024-AAACGGATCCTCCTAA-TS21_4_H,Marderstein_Nature_2024,AAACGGATCCTCCTAA,Marderstein_Nature_2024-TS21_4_H
...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C

In [9]:
new_mat.obs = df

In [ ]:
data_new = ad.concat([data, new_mat])
data_new

In [ ]:
data_new

In [ ]:
data_new.write_h5ad('./processed/data_new.h5ad')