# The first annotation using majority voting

In [2]:
import scanpy as sc
import pandas as pd
import numpy as np

## concat all

In [8]:
data = sc.read_h5ad('./processed/rna/raw/data.h5ad')
dat = data[data.obs['dataset'] != 'Hu_BioRxiv_2023']
dat

View of AnnData object with n_obs × n_vars = 1588148 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [9]:
del data

In [10]:
dat

View of AnnData object with n_obs × n_vars = 1588148 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [11]:
new = sc.read_h5ad('./processed/rna/raw/new.h5ad')
new

AnnData object with n_obs × n_vars = 53718 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_chetah_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_celltypist_level3', 'cellType_actinn_level3', 'cellType_scarch_level3', 'cellType_chetah_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_celltypist_level2', 'cellType_actinn_level2', 'cellType_scarch_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [12]:
new.obs = new.obs[dat.obs.columns.tolist()]

In [13]:
all = pd.concat([dat.obs, new.obs], axis=0)
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,T cells,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,T cells,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,T cells,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,NK cells,Memory B cells,CD16- NK cells,...,T cells,ILC,Node12,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Neutrophils,ILC,CD16+ NK cells,...,ILC,Promyelocytes,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Myelocytes,Helper T cells,Tcm/Naive helper T cells,...,Promyelocytes,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Myelocytes,MAIT cells,Double-negative thymocytes,...,T cells,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Myelocytes,Naive B cells,Classical monocytes,...,ILC,B cells,Promyelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome

In [14]:
all['cellType_raw_level2'].value_counts()

cellType_raw_level2
T cells                       786921
notAvailable                  349597
HSC/MPP                       122500
Monocytes                      96756
ILC                            89889
B cells                        75188
Erythroid                      46373
Double-negative thymocytes     21614
Megakaryocytes/platelets       10082
DC                              8437
B-cell lineage                  7959
pDC                             7048
Plasma cells                    4250
Megakaryocyte precursor         3918
Cycling cells                   3427
Macrophages                     2702
Granulocytes                    2684
Mast cells                      1694
DC precursor                     827
Name: count, dtype: int64

In [15]:
all.to_csv('./all_8.csv')

## compare origin and pred

In [16]:
all = pd.read_csv('./all_8.csv', index_col=0)
all

/tmp/ipykernel_1376528/2754020929.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  all = pd.read_csv('./all_8.csv', index_col=0)

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,T cells,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,T cells,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,T cells,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,NK cells,Memory B cells,CD16- NK cells,...,T cells,ILC,Node12,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Neutrophils,ILC,CD16+ NK cells,...,ILC,Promyelocytes,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Myelocytes,Helper T cells,Tcm/Naive helper T cells,...,Promyelocytes,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Myelocytes,MAIT cells,Double-negative thymocytes,...,T cells,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Myelocytes,Naive B cells,Classical monocytes,...,ILC,B cells,Promyelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome

In [17]:
all = all[all['cellType_raw_level2'] != 'notAvailable']
all

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,T cells,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,T cells,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,T cells,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,NK cells,Memory B cells,CD16- NK cells,...,T cells,ILC,Node12,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Neutrophils,ILC,CD16+ NK cells,...,ILC,Promyelocytes,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Myelocytes,Helper T cells,Tcm/Naive helper T cells,...,Promyelocytes,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Myelocytes,MAIT cells,Double-negative thymocytes,...,T cells,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Myelocytes,Naive B cells,Classical monocytes,...,ILC,B cells,Promyelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome

In [18]:
all.columns

Index(['dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1',
       'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3',
       'cellType_actinn_level3', 'cellType_celltypist_level3',
       'cellType_scmap_level3', 'cellType_singlecellnet_level3',
       'cellType_scpred_level3', 'cellType_singler_level3',
       'cellType_chetah_level3', 'cellType_scarch_level2',
       'cellType_actinn_level2', 'cellType_celltypist_level2',
       'cellType_scmap_level2', 'cellType_singlecellnet_level2',
       'cellType_scpred_level2', 'cellType_singler_level2',
       'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age',
       'age_stage', 'sex', 'technology'],
      dtype='object')

In [19]:
df = all[['cellType_scarch_level2',
       'cellType_actinn_level2', 'cellType_celltypist_level2',
       'cellType_scmap_level2', 'cellType_singlecellnet_level2',
       'cellType_scpred_level2', 'cellType_singler_level2',
       'cellType_chetah_level2','cellType_raw_level2']]

In [20]:
def calculate_similarity_ratio_all(df):
    last_col = df.iloc[:, -1]
    similarity_ratios = {}
    for col in df.columns[:-1]:  # 遍历前 n-1 列
        matches = (df[col] == last_col).sum()
        similarity_ratios[col] = matches / len(df)
    return similarity_ratios

In [21]:
calculate_similarity_ratio_all(df)

{'cellType_scarch_level2': 0.3342879849319298,
 'cellType_actinn_level2': 0.5641511171435668,
 'cellType_celltypist_level2': 0.8091852392961527,
 'cellType_scmap_level2': 0.45881236801316133,
 'cellType_singlecellnet_level2': 0.798645638021186,
 'cellType_scpred_level2': 0.8188983872552851,
 'cellType_singler_level2': 0.5479037259270322,
 'cellType_chetah_level2': 0.15520762318062262}

## majority voting

In [3]:
all = pd.read_csv('./all_8.csv', index_col=0)
all

/tmp/ipykernel_2081270/2754020929.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  all = pd.read_csv('./all_8.csv', index_col=0)

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,T cells,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,T cells,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,T cells,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,NK cells,Memory B cells,CD16- NK cells,...,T cells,ILC,Node12,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Neutrophils,ILC,CD16+ NK cells,...,ILC,Promyelocytes,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Myelocytes,Helper T cells,Tcm/Naive helper T cells,...,Promyelocytes,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Myelocytes,MAIT cells,Double-negative thymocytes,...,T cells,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Myelocytes,Naive B cells,Classical monocytes,...,ILC,B cells,Promyelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome

In [4]:
all.columns

Index(['dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1',
       'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3',
       'cellType_actinn_level3', 'cellType_celltypist_level3',
       'cellType_scmap_level3', 'cellType_singlecellnet_level3',
       'cellType_scpred_level3', 'cellType_singler_level3',
       'cellType_chetah_level3', 'cellType_scarch_level2',
       'cellType_actinn_level2', 'cellType_celltypist_level2',
       'cellType_scmap_level2', 'cellType_singlecellnet_level2',
       'cellType_scpred_level2', 'cellType_singler_level2',
       'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age',
       'age_stage', 'sex', 'technology'],
      dtype='object')

In [5]:
df = all[['cellType_actinn_level2', 'cellType_celltypist_level2',
       'cellType_singlecellnet_level2',
       'cellType_scpred_level2', 'cellType_singler_level2']]
df

,cellType_actinn_level2,cellType_celltypist_level2,cellType_singlecellnet_level2,cellType_scpred_level2,cellType_singler_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,T cells,T cells,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,T cells,T cells,T cells,T cells,ILC
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,T cells,ILC,T cells,T cells,ILC
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,ILC,T cells,T cells,T cells,Megakaryocyte precursor
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,T cells,T cells,T cells,T cells,T cells
...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,B cells,ILC,B cells,T cells,ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,ILC,ILC,B cells,ILC,Promyelocytes
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,T cells,T cells,T cells,Promyelocytes,HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,T cells,Double-negative thymocytes,B cells,T cells,HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,B cells,Monocytes,B cells,ILC,B cells

In [25]:
# 多数投票的矢量化实现
def majority_vote_vectorized(df):
    # 按行统计每个值的出现次数
    mode_counts = df.apply(lambda row: row.value_counts(), axis=1).fillna(0)

    # 找到出现最多的值及其出现次数
    max_counts = mode_counts.max(axis=1)
    majority_values = mode_counts.idxmax(axis=1)

    # 根据出现次数判断是否有效
    result = majority_values.where(max_counts >= 3, "notAvailable")
    return result

In [26]:
res = pd.DataFrame(majority_vote_vectorized(df))

In [27]:
res[0].value_counts()

0
T cells                     1021372
notAvailable                 165029
Monocytes                    158150
ILC                           98256
B cells                       98159
HSC/MPP                       57429
Erythroid                     18870
pDC                            8136
DC                             6203
Plasma cells                   4747
Mast cells                     2145
Early MK                       1766
Macrophages                     624
B-cell lineage                  529
Cycling cells                   405
Megakaryocyte precursor          14
Granulocytes                     11
Promyelocytes                    10
DC precursor                      9
ETP                               1
Megakaryocytes/platelets          1
Name: count, dtype: int64

In [75]:
res[0].value_counts()

0
T cells                     1021372
notAvailable                 165029
Monocytes                    158150
ILC                           98256
B cells                       98159
HSC/MPP                       57429
Erythroid                     18870
pDC                            8136
DC                             6203
Plasma cells                   4747
Mast cells                     2145
Early MK                       1766
Macrophages                     624
B-cell lineage                  529
Cycling cells                   405
Megakaryocyte precursor          14
Granulocytes                     11
Promyelocytes                    10
DC precursor                      9
ETP                               1
Megakaryocytes/platelets          1
Name: count, dtype: int64

In [76]:
res.to_csv('./5_3_level2.csv')

## Consensus ratio

In [20]:
all = pd.read_csv('./all_8.csv', index_col=0)
all

/tmp/ipykernel_2081270/2754020929.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  all = pd.read_csv('./all_8.csv', index_col=0)

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,T cells,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,T cells,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,T cells,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,NK cells,Memory B cells,CD16- NK cells,...,T cells,ILC,Node12,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Neutrophils,ILC,CD16+ NK cells,...,ILC,Promyelocytes,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Myelocytes,Helper T cells,Tcm/Naive helper T cells,...,Promyelocytes,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Myelocytes,MAIT cells,Double-negative thymocytes,...,T cells,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Myelocytes,Naive B cells,Classical monocytes,...,ILC,B cells,Promyelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome

In [21]:
df = all[['cellType_actinn_level2', 'cellType_celltypist_level2',
       'cellType_singlecellnet_level2',
       'cellType_scpred_level2', 'cellType_singler_level2']]
df

,cellType_actinn_level2,cellType_celltypist_level2,cellType_singlecellnet_level2,cellType_scpred_level2,cellType_singler_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,T cells,T cells,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,T cells,T cells,T cells,T cells,ILC
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,T cells,ILC,T cells,T cells,ILC
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,ILC,T cells,T cells,T cells,Megakaryocyte precursor
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,T cells,T cells,T cells,T cells,T cells
...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,B cells,ILC,B cells,T cells,ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,ILC,ILC,B cells,ILC,Promyelocytes
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,T cells,T cells,T cells,Promyelocytes,HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,T cells,Double-negative thymocytes,B cells,T cells,HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,B cells,Monocytes,B cells,ILC,B cells

In [22]:
l2 = pd.read_csv('5_3_level2.csv', index_col=0)
l2

                                                           0
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1         T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1         T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1         T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1         T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1         T cells
...                                                      ...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C  notAvailable
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C           ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C       T cells
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C  notAvailable
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C       B cells

[1641866 rows x 1 columns]

In [23]:
l2['0'].value_counts()

0
T cells                     1021372
notAvailable                 165029
Monocytes                    158150
ILC                           98256
B cells                       98159
HSC/MPP                       57429
Erythroid                     18870
pDC                            8136
DC                             6203
Plasma cells                   4747
Mast cells                     2145
Early MK                       1766
Macrophages                     624
B-cell lineage                  529
Cycling cells                   405
Megakaryocyte precursor          14
Granulocytes                     11
Promyelocytes                    10
DC precursor                      9
ETP                               1
Megakaryocytes/platelets          1
Name: count, dtype: int64

In [24]:
l2.index.tolist() == all.index.tolist()

True

In [13]:
df['mv'] = l2['0'].tolist()

/tmp/ipykernel_2081270/3387997955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mv'] = l2['0'].tolist()

In [14]:
df

,cellType_actinn_level2,cellType_celltypist_level2,cellType_singlecellnet_level2,cellType_scpred_level2,cellType_singler_level2,mv
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,T cells,T cells,T cells,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,T cells,T cells,T cells,T cells,ILC,T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,T cells,ILC,T cells,T cells,ILC,T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,ILC,T cells,T cells,T cells,Megakaryocyte precursor,T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,T cells,T cells,T cells,T cells,T cells,T cells
...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,B cells,ILC,B cells,T cells,ILC,notAvailable
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,ILC,ILC,B cells,ILC,Promyelocytes,ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,T cells,T cells,T cells,Promyelocytes,HSC/MPP,T cells
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,T cells,Double-negative thymocytes,B cells,T cells,HSC/MPP,notAvailable
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,B cells,Monocytes,B cells,ILC,B cells,B cells

In [15]:
def calculate_similarity_ratio_all(df):
    last_col = df.iloc[:, -1]
    similarity_ratios = {}
    for col in df.columns[:-1]:  # 遍历前 n-1 列
        matches = (df[col] == last_col).sum()
        similarity_ratios[col] = matches / len(df)
    return similarity_ratios

In [16]:
calculate_similarity_ratio_all(df)

{'cellType_actinn_level2': 0.5994131067943426,
 'cellType_celltypist_level2': 0.8509403325240915,
 'cellType_singlecellnet_level2': 0.8510280376108648,
 'cellType_scpred_level2': 0.8472073847683063,
 'cellType_singler_level2': 0.5569370460195899}

In [5]:
24*0.8510280376108648

20.424672902660753

In [17]:
# 比较原注释
l2['cellType_raw_level2'] = all['cellType_raw_level2'].tolist()
l2 = l2[all['cellType_raw_level2'] != 'notAvailable']
l2

,0,cellType_raw_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,T cells,T cells
...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,notAvailable,ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,ILC,Macrophages
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,T cells,Granulocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,notAvailable,HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,B cells,ILC

In [18]:
calculate_similarity_ratio_all(l2)

{'0': 0.8096820398848846}

## 3 method agree

In [63]:
all = pd.read_csv('./all_8.csv', index_col=0)
all = all[all['cellType_raw_level2'] != 'notAvailable']
all

/tmp/ipykernel_1117391/805070076.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  all = pd.read_csv('./all_8.csv', index_col=0)

,dataset,barcode,sample,cellType_raw,cellType_raw_level1,cellType_raw_level2,cellType_raw_level3,cellType_scarch_level3,cellType_actinn_level3,cellType_celltypist_level3,...,cellType_scpred_level2,cellType_singler_level2,cellType_chetah_level2,tissue,disease_name,disease,age,age_stage,sex,technology
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,Chen_Nat_Methods_2022,AAACAGCCAACTGGCT,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Regulatory T cells,Regulatory T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,Chen_Nat_Methods_2022,AAACATGCACAATTAC,Chen_Nat_Methods_2022-lane1,Treg,Lymphoid,T cells,Regulatory T cells,Neutrophils,Treg(diff),Tem/Effector helper T cells,...,T cells,ILC,HSC/MPP,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,Chen_Nat_Methods_2022,AAACATGCAGCACGTT,Chen_Nat_Methods_2022-lane1,Th17,Lymphoid,T cells,Type 17 helper T cells,Neutrophils,T cells,CD16- NK cells,...,T cells,ILC,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,Chen_Nat_Methods_2022,AAACATGCATATTGAC,Chen_Nat_Methods_2022-lane1,Th1,Lymphoid,T cells,Type 1 helper T cells,Neutrophils,ILC3,Tem/Trm cytotoxic T cells,...,T cells,Megakaryocyte precursor,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,Chen_Nat_Methods_2022,AAACCAACAATAGCAA,Chen_Nat_Methods_2022-lane1,TCM,Lymphoid,T cells,Tcm/Naive helper T cells,Neutrophils,Tcm/Naive helper T cells,Tcm/Naive helper T cells,...,T cells,T cells,T cells,blood,Healthy,healthy,notAvailable,notAvailable,notAvailable,NEAT-seq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,Marderstein_Nature_2024,TTTGTGTTCACGAATC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,NK cells,Memory B cells,CD16- NK cells,...,T cells,ILC,Node12,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,Marderstein_Nature_2024,TTTGTGTTCATGGCCA,Marderstein_Nature_2024-H_7_C,Pro-inflammatory macrophages,Myeloid,Macrophages,Macrophages,Neutrophils,ILC,CD16+ NK cells,...,ILC,Promyelocytes,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,Marderstein_Nature_2024,TTTGTGTTCTGTGCAG,Marderstein_Nature_2024-H_7_C,Neutrophils,Myeloid,Granulocytes,Neutrophils,Myelocytes,Helper T cells,Tcm/Naive helper T cells,...,Promyelocytes,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Marderstein_Nature_2024,TTTGTTGGTAGGTTTG,Marderstein_Nature_2024-H_7_C,HSCs,HSC/MPP,HSC/MPP,HSC/MPP,Myelocytes,MAIT cells,Double-negative thymocytes,...,T cells,HSC/MPP,Unassigned,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Marderstein_Nature_2024,TTTGTTGGTTAACGGC,Marderstein_Nature_2024-H_7_C,NK cells,Lymphoid,ILC,NK cells,Myelocytes,Naive B cells,Classical monocytes,...,ILC,B cells,Promyelocytes,fetal liver,Healthy,Healthy,14 pcw,0_1,notAvailable,10x multiome

In [64]:
test = all[['cellType_celltypist_level2','cellType_singlecellnet_level2','cellType_scpred_level2']]
test

,cellType_celltypist_level2,cellType_singlecellnet_level2,cellType_scpred_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,ILC,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,T cells,T cells,T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,T cells,T cells,T cells
...,...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,ILC,B cells,T cells
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,ILC,B cells,ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,T cells,T cells,Promyelocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,Double-negative thymocytes,B cells,T cells
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,Monocytes,B cells,ILC

In [65]:
# Vectorized implementation of majority voting
def majority_vote_vectorized(df):
    # Count the frequency of each value per row
    mode_counts = df.apply(lambda row: row.value_counts(), axis=1).fillna(0)

    # Find the most frequent value and its occurrence count
    max_counts = mode_counts.max(axis=1)
    majority_values = mode_counts.idxmax(axis=1)

    # Determine validity based on the occurrence count
    # (Retain the value if it appears at least twice, otherwise mark as "notAvailable")
    result = majority_values.where(max_counts >= 2, "notAvailable")
    return result

In [66]:
# level2
res = pd.DataFrame(majority_vote_vectorized(test))
res[0].value_counts()

0
T cells                       823270
Monocytes                     108465
notAvailable                   93748
ILC                            81243
B cells                        80159
HSC/MPP                        55500
Erythroid                      19719
pDC                             7214
Plasma cells                    5296
DC                              4154
Mast cells                      3592
Macrophages                     3477
Megakaryocyte precursor         2360
Early MK                        2264
B-cell lineage                  1471
ETP                              144
Cycling cells                    118
Promyelocytes                     28
Double-negative thymocytes        10
DC precursor                       9
Granulocytes                       8
Megakaryocytes/platelets           6
Erythrocytes                       6
Double-positive thymocytes         4
Myelocytes                         2
Mono-mac                           2
Name: count, dtype: int64

In [67]:
res['cellType_raw_level2'] = all['cellType_raw_level2'].tolist()
res

,0,cellType_raw_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1,T cells,T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1,T cells,T cells
...,...,...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C,notAvailable,ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C,ILC,Macrophages
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C,T cells,Granulocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C,notAvailable,HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C,notAvailable,ILC

In [68]:
def calculate_similarity_ratio_all(df):
    last_col = df.iloc[:, -1]
    similarity_ratios = {}
    for col in df.columns[:-1]:  
        matches = (df[col] == last_col).sum()
        similarity_ratios[col] = matches / len(df)
    return similarity_ratios

In [69]:
calculate_similarity_ratio_all(res)

{0: 0.8248151120238898}

# The second annotation using transfer

In [3]:
import scanpy as sc
import pandas as pd

## Read data, add mv results

In [2]:
data = sc.read_h5ad('./processed/rna/data_new.h5ad')
data

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [5]:
mv = pd.read_csv('./processed/ann/5_3_level2.csv', index_col=0)
mv

                                                           0
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1         T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1         T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1         T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1         T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1         T cells
...                                                      ...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C  notAvailable
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C           ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C       T cells
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C  notAvailable
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C       B cells

[1641866 rows x 1 columns]

In [6]:
data.obs_names.tolist() == mv.index.tolist()

True

In [7]:
data.obs['mv'] = mv['0'].tolist()

In [8]:
dat = data[data.obs['mv'] != 'notAvailable']
dat

View of AnnData object with n_obs × n_vars = 1476837 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'mv'

In [11]:
dat.obs['cellType_raw'].value_counts()

cellType_raw
notAvailable      324948
CD4 Memory        220163
CD4 T Naive        98300
CD4 Naive          56593
NK                 53135
                   ...
14_Unk                 7
15_CLP.2               6
11_CD14.Mono.1         5
04_Early.Baso          3
26_Unk                 1
Name: count, Length: 153, dtype: int64

In [16]:
1476837-324948

1151889

In [13]:
dat = data[data.obs['mv'] == 'notAvailable']
dat

View of AnnData object with n_obs × n_vars = 165029 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'mv'

In [14]:
dat.obs['cellType_raw'].value_counts()

cellType_raw
notAvailable      24176
HSPC              16178
MEMPs             12161
CD4 Memory         6393
Megakaryocytes     5051
                  ...
20_CD4.N1             2
cDC1                  2
09_pDC                1
17_B                  1
Treg_1                1
Name: count, Length: 147, dtype: int64

In [15]:
165029-24176

140853

In [ ]:
import matplotlib.pyplot as plt

# 数据
sizes = [140853, 24176, 1151889, 324948]
labels = ['165029', '24176', '1476837', '324948']
colors = ['#FF9999', '#66B2FF', '#99FF99', '#FFCC99']  # 四种颜色
explode = (0, 0, 0.1, 0)  # 突出显示第三个部分（1476837）

# 绘制饼图
plt.figure(figsize=(8, 8))
plt.pie(sizes,  labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.title('Pie Chart of Four Values')
plt.axis('equal')  # 确保饼图是圆形

# 保存并显示
plt.savefig('pie_chart_four_values.pdf')
plt.show()

print("饼图已保存为 'pie_chart_four_values.png'")

## train model

In [23]:
import celltypist

In [24]:
sc.pp.normalize_total(dat, target_sum=1e4)
sc.pp.log1p(dat)
sc.pp.highly_variable_genes(dat, min_mean=0.0125, max_mean=3, min_disp=0.5, batch_key='sample')

... storing 'mv' as categorical

In [25]:
adata = dat[:, dat.var.highly_variable]
adata

View of AnnData object with n_obs × n_vars = 1476837 × 3525
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'mv'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'log1p', 'hvg'

In [26]:
# new_model = celltypist.train(adata, 
#                              labels = 'mv', 
#                              check_expression = False,
#                              use_SGD = True,
#                              mini_batch = True)

🍳 Preparing data before training
🔬 Input data has 1476837 cells and 3525 genes
⚖️ Scaling input data
🏋️ Training data using mini-batch SGD logistic regression
⏳ Epochs: [1/10]
⏳ Epochs: [2/10]
⏳ Epochs: [3/10]
⏳ Epochs: [4/10]
⏳ Epochs: [5/10]
⏳ Epochs: [6/10]
⏳ Epochs: [7/10]
⏳ Epochs: [8/10]
⏳ Epochs: [9/10]
⏳ Epochs: [10/10]
✅ Model training done!

In [27]:
new_model.write('./model.pkl')

## annotate cell types

In [ ]:
# new_model = models.Model.load('./model.pkl')

In [28]:
da = data[data.obs['mv'] == 'notAvailable']
da

View of AnnData object with n_obs × n_vars = 165029 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'mv'

In [29]:
sc.pp.normalize_total(da, target_sum=1e4)
sc.pp.log1p(da)

In [30]:
predictions = celltypist.annotate(da, model = new_model, majority_voting=True)

🔬 Input data has 165029 cells and 36601 genes
🔗 Matching reference genes in the model
🧬 3525 features used for prediction
⚖️ Scaling input data
🖋️ Predicting labels
✅ Prediction done!
👀 Can not detect a neighborhood graph, will construct one before the over-clustering
/home/qiaolibo/miniconda3/envs/scanpy/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
⛓️ Over-clustering input data with resolution set to 25
IOStream.flush timed out
IOStream.flush timed out
IOStream.flush timed out
🗳️ Majority voting the predictions
✅ Majority voting done!

In [32]:
da_a = predictions.to_adata()

In [33]:
da_a

AnnData object with n_obs × n_vars = 165029 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'mv', 'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score'
    uns: 'log1p', 'neighbors', 'over_clustering'
    obsm: 'X_pca'
    obsp: 'connectivities', 'distances'

In [38]:
dd = da_a.obs[['predicted_labels']]
dd

                                               predicted_labels
Chen_Nat_Methods_2022-AAACGGATCGAGCTAT-lane1            T cells
Chen_Nat_Methods_2022-AAATCCGGTTGGTTGA-lane1            T cells
Chen_Nat_Methods_2022-AACGCTAGTAAATTGC-lane1            T cells
Chen_Nat_Methods_2022-AAGACAAGTAAGCACC-lane1            T cells
Chen_Nat_Methods_2022-AAGCTTGGTTTGGGTA-lane1            T cells
...                                                         ...
Marderstein_Nature_2024-TTTGTGGCAAGGATTA-H_7_C          T cells
Marderstein_Nature_2024-TTTGTGGCACTAAGAA-H_7_C          T cells
Marderstein_Nature_2024-TTTGTGGCATCCCGCT-H_7_C          T cells
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C              ILC
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C          T cells

[165029 rows x 1 columns]

In [39]:
dd.to_csv('./two_transfer.csv')

## Get all annotation

In [56]:
data = sc.read_h5ad('./processed/rna/data_new.h5ad')
data

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology'

In [57]:
mv = pd.read_csv('./5_3_level2.csv', index_col=0)
mv = mv[mv['0'] != 'notAvailable']
mv

                                                      0
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1    T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1    T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1    T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1    T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1    T cells
...                                                 ...
Marderstein_Nature_2024-TTTGTCCCACCAACCG-H_7_C  B cells
Marderstein_Nature_2024-TTTGTGAAGCCTGACA-H_7_C  B cells
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C      ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C  T cells
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C  B cells

[1476837 rows x 1 columns]

In [58]:
two = pd.read_csv('./two_transfer.csv', index_col=0)
two.columns = ['0']
two

                                                      0
Chen_Nat_Methods_2022-AAACGGATCGAGCTAT-lane1    T cells
Chen_Nat_Methods_2022-AAATCCGGTTGGTTGA-lane1    T cells
Chen_Nat_Methods_2022-AACGCTAGTAAATTGC-lane1    T cells
Chen_Nat_Methods_2022-AAGACAAGTAAGCACC-lane1    T cells
Chen_Nat_Methods_2022-AAGCTTGGTTTGGGTA-lane1    T cells
...                                                 ...
Marderstein_Nature_2024-TTTGTGGCAAGGATTA-H_7_C  T cells
Marderstein_Nature_2024-TTTGTGGCACTAAGAA-H_7_C  T cells
Marderstein_Nature_2024-TTTGTGGCATCCCGCT-H_7_C  T cells
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C      ILC
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C  T cells

[165029 rows x 1 columns]

In [59]:
all = pd.concat([mv, two], axis=0)
all = all.reindex(data.obs_names.tolist())
all

                                                      0
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1    T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1    T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1    T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1    T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1    T cells
...                                                 ...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C      ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C      ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C  T cells
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C  T cells
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C  B cells

[1641866 rows x 1 columns]

In [66]:
classification_dict = {
    'Granulocytes': 'Monocytes',
    'Promyelocytes': 'Monocytes',
    'DC precursor': 'DC',
    'ETP': 'T cells',
    'Megakaryocytes/platelets': 'Early MK',
    'Megakaryocyte precursor': 'Early MK'
}

In [67]:
all.replace(classification_dict, inplace=True)

In [68]:
all['0'].value_counts()

0
T cells           1115932
Monocytes          169481
ILC                106651
B cells            103190
HSC/MPP             88479
Erythroid           30220
pDC                  8876
DC                   7078
Plasma cells         4796
Mast cells           2912
Early MK             2693
Macrophages           624
B-cell lineage        529
Cycling cells         405
Name: count, dtype: int64

In [69]:
data.obs_names.tolist() == all.index.tolist()

True

In [70]:
data.obs['final_ann'] = all['0'].tolist()

In [71]:
data.obs['final_ann'].value_counts()

final_ann
T cells           1115932
Monocytes          169481
ILC                106651
B cells            103190
HSC/MPP             88479
Erythroid           30220
pDC                  8876
DC                   7078
Plasma cells         4796
Mast cells           2912
Early MK             2693
Macrophages           624
B-cell lineage        529
Cycling cells         405
Name: count, dtype: int64

In [72]:
data

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann'

In [73]:
data.write_h5ad('./processed/adata.h5ad')

... storing 'final_ann' as categorical

## Compare the original annotation with the individual ratio plots of all cells

In [40]:
data = sc.read_h5ad('./processed/adata.h5ad')
data

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann'

In [56]:
data

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann'

In [5]:
data.obs['cellType_raw_level2'].value_counts()

cellType_raw_level2
T cells                       786921
notAvailable                  349597
HSC/MPP                       122500
Monocytes                      96756
ILC                            89889
B cells                        75188
Erythroid                      46373
Double-negative thymocytes     21614
Megakaryocytes/platelets       10082
DC                              8437
B-cell lineage                  7959
pDC                             7048
Plasma cells                    4250
Megakaryocyte precursor         3918
Cycling cells                   3427
Macrophages                     2702
Granulocytes                    2684
Mast cells                      1694
DC precursor                     827
Name: count, dtype: int64

In [57]:
classification_dict = {
    'Double-negative thymocytes': 'T cells',
    'Megakaryocytes/platelets': 'Early MK',
    'Megakaryocyte precursor': 'Early MK',
    'Granulocytes': 'Monocytes',
    'DC precursor': 'DC'
}

In [58]:
other = data.obs[['cellType_raw_level2']]
other

                                               cellType_raw_level2
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1               T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1               T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1               T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1               T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1               T cells
...                                                            ...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C                 ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C         Macrophages
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C        Granulocytes
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C             HSC/MPP
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C                 ILC

[1641866 rows x 1 columns]

In [59]:
other.replace(classification_dict, inplace=True)

/tmp/ipykernel_3443889/1028619219.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other.replace(classification_dict, inplace=True)

In [60]:
other['cellType_raw_level2'].value_counts()

cellType_raw_level2
T cells           808535
notAvailable      349597
HSC/MPP           122500
Monocytes          99440
ILC                89889
B cells            75188
Erythroid          46373
Early MK           14000
DC                  9264
B-cell lineage      7959
pDC                 7048
Plasma cells        4250
Cycling cells       3427
Macrophages         2702
Mast cells          1694
Name: count, dtype: int64

In [61]:
data.obs['cellType_raw_level2'] = other['cellType_raw_level2'].tolist()

In [62]:
data.write_h5ad('./processed/adata.h5ad')

In [13]:
other['final_ann'] = data.obs['final_ann'].tolist()
other

/tmp/ipykernel_3443889/1532817401.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other['final_ann'] = data.obs['final_ann'].tolist()

                                               cellType_raw_level2 final_ann
Chen_Nat_Methods_2022-AAACAGCCAACTGGCT-lane1               T cells   T cells
Chen_Nat_Methods_2022-AAACATGCACAATTAC-lane1               T cells   T cells
Chen_Nat_Methods_2022-AAACATGCAGCACGTT-lane1               T cells   T cells
Chen_Nat_Methods_2022-AAACATGCATATTGAC-lane1               T cells   T cells
Chen_Nat_Methods_2022-AAACCAACAATAGCAA-lane1               T cells   T cells
...                                                            ...       ...
Marderstein_Nature_2024-TTTGTGTTCACGAATC-H_7_C                 ILC       ILC
Marderstein_Nature_2024-TTTGTGTTCATGGCCA-H_7_C         Macrophages       ILC
Marderstein_Nature_2024-TTTGTGTTCTGTGCAG-H_7_C           Monocytes   T cells
Marderstein_Nature_2024-TTTGTTGGTAGGTTTG-H_7_C             HSC/MPP   T cells
Marderstein_Nature_2024-TTTGTTGGTTAACGGC-H_7_C                 ILC   B cells

[1641866 rows x 2 columns]

In [15]:
# Initialize an empty dictionary to store results
results = {}

# Get all unique categories from the 'final_ann' column
categories = other['final_ann'].unique()

# Iterate through each category to calculate ratios
for category in categories:
    # Filter data for the current category
    subset = other[other['final_ann'] == category]
    
    # Total count of entries in this category
    total = len(subset)
    
    # Calculate the ratio of matches (where 'cellType_raw_level2' matches 'final_ann')
    match_ratio = (subset['cellType_raw_level2'] == subset['final_ann']).sum() / total
    
    # Calculate the ratio of entries marked as 'notAvailable'
    not_available_ratio = (subset['cellType_raw_level2'] == 'notAvailable').sum() / total
    
    # Calculate the remaining ratio (i.e., 1 - match ratio - notAvailable ratio)
    other_ratio = 1 - match_ratio - not_available_ratio
    
    # Store the calculated metrics in the results dictionary
    results[category] = {
        'match_ratio': match_ratio,
        'not_available_ratio': not_available_ratio,
        'other_ratio': other_ratio
    }

# Convert the results dictionary to a DataFrame for easier viewing
result_df = pd.DataFrame(results).T
result_df.index.name = 'Category'

# Print the final DataFrame
print(result_df)

                match_ratio  not_available_ratio  other_ratio
Category
T cells            0.705920             0.216175     0.077904
ILC                0.569981             0.182361     0.247658
Monocytes          0.550433             0.329093     0.120474
B cells            0.697335             0.209652     0.093013
Mast cells         0.174107             0.029533     0.796360
HSC/MPP            0.824659             0.056771     0.118571
DC                 0.679712             0.268296     0.051992
Macrophages        0.030449             0.456731     0.512821
Plasma cells       0.855088             0.080275     0.064637
pDC                0.638125             0.176093     0.185782
Erythroid          0.631899             0.068564     0.299537
Early MK           0.873375             0.020795     0.105830
Cycling cells      0.646914             0.128395     0.224691
B-cell lineage     0.491493             0.153119     0.355388

In [19]:
result_df['Category'] = result_df.index.tolist()
result_df

                match_ratio  not_available_ratio  other_ratio        Category
Category
T cells            0.705920             0.216175     0.077904         T cells
ILC                0.569981             0.182361     0.247658             ILC
Monocytes          0.550433             0.329093     0.120474       Monocytes
B cells            0.697335             0.209652     0.093013         B cells
Mast cells         0.174107             0.029533     0.796360      Mast cells
HSC/MPP            0.824659             0.056771     0.118571         HSC/MPP
DC                 0.679712             0.268296     0.051992              DC
Macrophages        0.030449             0.456731     0.512821     Macrophages
Plasma cells       0.855088             0.080275     0.064637    Plasma cells
pDC                0.638125             0.176093     0.185782             pDC
Erythroid          0.631899             0.068564     0.299537       Erythroid
Early MK           0.873375             0.020795     0.105830        Early MK
Cycling cells      0.646914             0.128395     0.224691   Cycling cells
B-cell lineage     0.491493             0.153119     0.355388  B-cell lineage

In [22]:
import matplotlib.pyplot as plt

In [29]:
df = result_df.sort_values(by='match_ratio', ascending=False)
df

                match_ratio  not_available_ratio  other_ratio        Category
Category
Early MK           0.873375             0.020795     0.105830        Early MK
Plasma cells       0.855088             0.080275     0.064637    Plasma cells
HSC/MPP            0.824659             0.056771     0.118571         HSC/MPP
T cells            0.705920             0.216175     0.077904         T cells
B cells            0.697335             0.209652     0.093013         B cells
DC                 0.679712             0.268296     0.051992              DC
Cycling cells      0.646914             0.128395     0.224691   Cycling cells
pDC                0.638125             0.176093     0.185782             pDC
Erythroid          0.631899             0.068564     0.299537       Erythroid
ILC                0.569981             0.182361     0.247658             ILC
Monocytes          0.550433             0.329093     0.120474       Monocytes
B-cell lineage     0.491493             0.153119     0.355388  B-cell lineage
Mast cells         0.174107             0.029533     0.796360      Mast cells
Macrophages        0.030449             0.456731     0.512821     Macrophages

In [ ]:
# Plot the stacked bar chart
fig, ax = plt.subplots(figsize=(10, 6))

# Plot each segment
ax.bar(df['Category'], df['match_ratio'], label='Match Ratio', color='#32cd32')
ax.bar(df['Category'], df['not_available_ratio'], 
       bottom=df['match_ratio'], label='Not Available Ratio', color='#4682b4')
ax.bar(df['Category'], df['other_ratio'], 
       bottom=df['match_ratio'] + df['not_available_ratio'], label='Other Ratio', color='#ff0000')

# Add title and axis labels
# ax.set_title('Proportion of Ratios by Category', fontsize=16)
# ax.set_xlabel('Category', fontsize=12)
# ax.set_ylabel('Proportion', fontsize=12)
ax.set_ylim(0, 1)  # Set the y-axis limits from 0 to 1
ax.legend(title='Ratio Type')

# Display grid lines
# ax.grid(axis='y', linestyle='--', alpha=0.7)

# Save as PDF
plt.tight_layout()
plt.savefig('stacked_bar_chart.pdf')

# Show the plot
plt.show()

In [31]:
# total
# notAvailable      
349597/1641866

0.212926633476788

In [33]:
def calculate_similarity_ratio_all(df):
    last_col = df.iloc[:, -1]
    similarity_ratios = {}
    for col in df.columns[:-1]:  
        matches = (df[col] == last_col).sum()
        similarity_ratios[col] = matches / len(df)
    return similarity_ratios

In [34]:
calculate_similarity_ratio_all(other)

{'cellType_raw_level2': 0.6844839956488532}

In [35]:
1-0.212926633476788-0.6844839956488532

0.10258937087435882

In [36]:
24*0.6844839956488532

16.427615895572476

In [37]:
24*0.212926633476788

5.110239203442912

In [38]:
24*0.10258937087435882

2.4621449009846117

## The ratio of all cells

In [63]:
adata = sc.read_h5ad('./processed/adata.h5ad')
adata

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann'

In [64]:
final_ann = pd.DataFrame(adata.obs['final_ann'].value_counts())
final_ann['final'] = final_ann.index.tolist()
final_ann.sort_values(by='final', inplace=True)
final_ann['color'] = ['#1f77b4',
               '#ff7f0e',
               '#279e68',
               '#d62728',
               '#aa40fc',
               '#8c564b',
               '#e377c2',
               '#b5bd61',
               '#17becf',
               '#aec7e8',
               '#ffbb78',
               '#98df8a',
               '#ff9896',
               '#c5b0d5']
final_ann.sort_values(by='count', inplace=True, ascending=False)
final_ann[['count', 'color']]

                  count    color
final_ann
T cells         1115932  #ff9896
Monocytes        169481  #ffbb78
ILC              106651  #b5bd61
B cells          103190  #1f77b4
HSC/MPP           88479  #e377c2
Erythroid         30220  #8c564b
pDC                8876  #c5b0d5
DC                 7078  #d62728
Plasma cells       4796  #98df8a
Mast cells         2912  #aec7e8
Early MK           2693  #aa40fc
Macrophages         624  #17becf
B-cell lineage      529  #ff7f0e
Cycling cells       405  #279e68

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

data = {
    'Cell Type': ['T cells', 'Monocytes', 'ILC', 'B cells', 'HSC/MPP', 'Erythroid', 'pDC', 
                  'DC', 'Plasma cells', 'Mast cells', 'Early MK', 'Macrophages', 
                  'B-cell lineage', 'Cycling cells'],
    'Count': [1115932, 169481, 106651, 103190, 88479, 30220, 8876, 7078, 4796, 
              2912, 2693, 624, 529, 405],
    'Color': ['#ff9896', '#ffbb78', '#b5bd61', '#1f77b4', '#e377c2', '#8c564b', '#c5b0d5', 
              '#d62728', '#98df8a', '#aec7e8', '#aa40fc', '#17becf', '#ff7f0e', '#279e68']
}

df = pd.DataFrame(data)

plt.figure(figsize=(8, 8))
plt.pie(df['Count'], labels=df['Cell Type'], autopct='%1.1f%%', startangle=90, colors=df['Color'])
plt.title('Cell Type Distribution')
plt.axis('equal')  
plt.savefig('cell_type_distribution_1.pdf', format='pdf')
plt.show()

In [5]:
30220/1641866

0.01840588696032441

In [65]:
final_ann = pd.DataFrame(adata.obs['cellType_raw_level2'].value_counts())
final_ann['final'] = final_ann.index.tolist()
final_ann.sort_values(by='final', inplace=True)
final_ann

                      count           final
cellType_raw_level2
B cells               75188         B cells
B-cell lineage         7959  B-cell lineage
Cycling cells          3427   Cycling cells
DC                     9264              DC
Early MK              14000        Early MK
Erythroid             46373       Erythroid
HSC/MPP              122500         HSC/MPP
ILC                   89889             ILC
Macrophages            2702     Macrophages
Mast cells             1694      Mast cells
Monocytes             99440       Monocytes
Plasma cells           4250    Plasma cells
T cells              808535         T cells
notAvailable         349597    notAvailable
pDC                    7048             pDC

In [66]:
final_ann['color'] = ['#1f77b4',
               '#ff7f0e',
               '#279e68',
               '#d62728',
               '#aa40fc',
               '#8c564b',
               '#e377c2',
               '#b5bd61',
               '#17becf',
               '#aec7e8',
               '#ffbb78',
               '#98df8a',
               '#ff9896',
               '#cccecf',
               '#c5b0d5']
final_ann.sort_values(by='count', inplace=True, ascending=False)
final_ann[['count', 'color']]

                      count    color
cellType_raw_level2
T cells              808535  #ff9896
notAvailable         349597  #cccecf
HSC/MPP              122500  #e377c2
Monocytes             99440  #ffbb78
ILC                   89889  #b5bd61
B cells               75188  #1f77b4
Erythroid             46373  #8c564b
Early MK              14000  #aa40fc
DC                     9264  #d62728
B-cell lineage         7959  #ff7f0e
pDC                    7048  #c5b0d5
Plasma cells           4250  #98df8a
Cycling cells          3427  #279e68
Macrophages            2702  #17becf
Mast cells             1694  #aec7e8

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

# 数据
data = {
    'Cell Type': ['T cells', 'notAvailable', 'HSC/MPP', 'Monocytes', 'ILC', 'B cells', 'Erythroid', 
                  'Early MK', 'DC', 'B-cell lineage', 'pDC', 'Plasma cells', 'Cycling cells', 
                  'Macrophages', 'Mast cells'],
    'Count': [808535, 349597, 122500, 99440, 89889, 75188, 46373, 14000, 9264, 7959, 7048, 
              4250, 3427, 2702, 1694],
    'Color': ['#ff9896', '#cccecf', '#e377c2', '#ffbb78', '#b5bd61', '#1f77b4', '#8c564b', '#aa40fc',
              '#d62728', '#ff7f0e', '#c5b0d5', '#98df8a', '#279e68', '#17becf', '#aec7e8']
}

# 创建 DataFrame
df = pd.DataFrame(data)

# 绘制饼图
plt.figure(figsize=(8, 8))
plt.pie(df['Count'], labels=df['Cell Type'], autopct='%1.1f%%', startangle=90, colors=df['Color'])
plt.title('Cell Type Distribution')
plt.axis('equal')  # 保证饼图是圆形
plt.savefig('cell_type_distribution_2.pdf', format='pdf')
plt.show()

In [6]:
14000/1641866

0.0085268834362853

## marker gene

In [15]:
data = sc.read_h5ad('./processed/adata.h5ad')
data

AnnData object with n_obs × n_vars = 1641866 × 36601
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann'

In [16]:
sc.pp.normalize_total(data, target_sum=1e4)
sc.pp.log1p(data)

In [17]:
data.obs['final_ann'].value_counts()

final_ann
T cells           1115932
Monocytes          169481
ILC                106651
B cells            103190
HSC/MPP             88479
Erythroid           30220
pDC                  8876
DC                   7078
Plasma cells         4796
Mast cells           2912
Early MK             2693
Macrophages           624
B-cell lineage        529
Cycling cells         405
Name: count, dtype: int64

In [18]:
# Sort by distinction
marker_genes_dict = {
    "B cells": ["BANK1","MS4A1", "CD79A"],
    "B-cell lineage": ["DNTT", "MME", "VPREB1"], 
    "Cycling cells": ["MKI67", "TOP2A", "CDK1"],
    "DC": ["HLA-DRA",  "CST3", "ITGAX"],
    "Early MK": [ "ITGA2B", "ITGB3","PF4"],
    "Erythroid": [ "HBA1", "HBA2", "ALAS2"],
    "HSC/MPP": [ "PROM1", "SPINK2", "CD34"],
    "ILC": ["CD247", "GNLY", "NKG7"], 
    "Macrophages": ["RBM47", "DOCK4", "PLAUR"],
    "Mast cells": ["KIT", "CPA3","TPSAB1"],
    "Monocytes": [ "VCAN", "LYZ", "S100A9"],
    "Plasma cells": ["JCHAIN", "MZB1","XBP1"],
    "T cells": ["IL7R", "ANK3","LEF1"],
    "pDC": ["TCF4", "IL3RA", "CLEC4C"]
}

In [19]:
adata = sc.read_h5ad('./dendrogram.h5ad')
adata

AnnData object with n_obs × n_vars = 1641866 × 3568
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'dendrogram_final_ann', 'hvg', 'log1p', 'pca'
    obsm: 'X_pca', 'X_pca_harmony'
    varm: 'PCs'

In [20]:
data.uns['dendrogram_final_ann'] = adata.uns['dendrogram_final_ann']

In [ ]:
sc.pl.dotplot(data, marker_genes_dict, groupby='final_ann', dendrogram=True, save='_marker')

In [ ]:
# combine DEG

In [28]:
sc.tl.rank_genes_groups(data, "final_ann", method="t-test")

In [40]:
pd.DataFrame(data.uns["rank_genes_groups"]["names"]).head(20)[['T cells']]

    T cells
0     CAMK4
1    BCL11B
2      IL7R
3    THEMIS
4      LEF1
5      TC2N
6       ITK
7      ANK3
8    INPP4B
9      TCF7
10    PDE3B
11    PRKCA
12      CD6
13    SKAP1
14    NELL2
15    PRKCH
16  SERINC5
17     TRAC
18    DOCK9
19   CDC14A

In [ ]:
sc.pl.dotplot(data, [
    'IL7R',
    'THEMIS',
    'LEF1',
    'TCF7',
    'ITK',
    'SKAP1',
    'TRAC',
    'CD6',
    'PRKCA',
    'ANK3'
], groupby='final_ann')

## dendrogram

In [ ]:
# adata = sc.read_h5ad('./processed/adata.h5ad')
# sc.pp.calculate_qc_metrics(adata,inplace=True)
# sc.pp.normalize_total(adata, target_sum=1e4)
# sc.pp.log1p(adata)
# sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5, batch_key='sample')
# adata = adata[:, adata.var.highly_variable]
# sc.pp.scale(adata, max_value=10)
# sc.tl.pca(adata, svd_solver='arpack')

# sce.pp.harmony_integrate(adata, 'sample')
# adata.obsm['X_pca'] = adata.obsm['X_pca_harmony']

# sc.tl.dendrogram(adata, "final_ann")

# adata.write_h5ad('./dendrogram.h5ad')

In [12]:
data = sc.read_h5ad('./dendrogram.h5ad')
data

AnnData object with n_obs × n_vars = 1641866 × 3568
    obs: 'dataset', 'barcode', 'sample', 'cellType_raw', 'cellType_raw_level1', 'cellType_raw_level2', 'cellType_raw_level3', 'cellType_scarch_level3', 'cellType_actinn_level3', 'cellType_celltypist_level3', 'cellType_scmap_level3', 'cellType_singlecellnet_level3', 'cellType_scpred_level3', 'cellType_singler_level3', 'cellType_chetah_level3', 'cellType_scarch_level2', 'cellType_actinn_level2', 'cellType_celltypist_level2', 'cellType_scmap_level2', 'cellType_singlecellnet_level2', 'cellType_scpred_level2', 'cellType_singler_level2', 'cellType_chetah_level2', 'tissue', 'disease_name', 'disease', 'age', 'age_stage', 'sex', 'technology', 'final_ann', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'dendrogram_final_ann', 'hvg', 'log1p', 'pca'
    obsm: 'X_pca', 'X_pca_harmony'
    varm: 'PCs'

In [ ]:
sc.pl.dendrogram(data, 'final_ann')